---
title: "Bivariate Viz"
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
# Load needed packages
library(tidyverse)
library(ggplot2)
```

```{r}
# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") 
```

```{r}
#| fig-cap: "Comparison of morning versus afternoon temperatures in 3 Australian towns. Created by Zach Marshak, Feb. 2025, data source Mac-Stat Git Hub."
#| fig-alt: "A scatter plot of Temperatures of the Australian Cities of Wollongong, Hobart, and Uluru. The Temperature in Celcius at 9 am is on the x-axis, and the Temperature in Celcius at 3 pm is on the y-axis. There is a positive relationship between the two"
ggplot(weather, aes(x = temp9am, y = temp3pm))+
  geom_point(alpha = 0.5)+
  theme_minimal()+
  labs( x = "Temperature at 9 am (celcius)", y = "Temperature at 3 pm (celcius)", title = "Tempatures in Wollongong, Hobart, and Uluru Australia" )
```
