---
title: "Trivariate Viz"
---

Use this file to generate a professional looking **trivariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
# Load needed packages
library(tidyverse)
library(ggplot2)
```

```{r}
# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") 
```

```{r}
#| fig-cap: "Scatter plot of morning versus afternoon temperatures in three Australian cities. Created by Zach Marshak, Feb. 2025, data source Mac-Stat Git Hub."
#| fig-alt: "Scatter plot of temperatures in celcius in three Australian cities. The cities Hobart, Uluru, and Wollongong are each a different colored point, the x axis is temperatures at 9 am and the y axis is temperatures at 3 pm. Uluru has the typically highest temperatures, followed by Wollongong then Hobart"
ggplot(weather, aes(x = temp9am, y = temp3pm, color = location))+
  geom_point(alpha = 0.5)+
   scale_color_viridis_d()+
  labs( x = "Temperature at 9 am (celcius)", y = "Temperature at 3 pm (celcius)", color = "City", Title = "Temperatures in Australian Cities")
```
