<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>18&nbsp; Reshaping – COMP/STAT112 Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ica/ica-joining.html" rel="next">
<link href="../ica/Dates.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../style/custom.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ica/quarto-demo.html">In-class Activities</a></li><li class="breadcrumb-item"><a href="../ica/ica-Reshaping.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Reshaping</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Zach Marshak</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Best Work</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-uni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Univariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-bi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bivariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-tri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Trivariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-quad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Quadvariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-spatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/Exam_1_vis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exam 1 Visulization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/Food_Consumpption_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Food Consumption 2</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Summary</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Summary/Exam_1_Review_Sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exam 1 Review Sheet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Summary/Exam_2_Review_sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Exam 2 review sheet</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">In-class Activities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/quarto-demo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">My first Quarto document</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-uni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Univariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-bi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bivariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Mulivariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-spatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Spatial Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/effective-vis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Effective Vis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/Dates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Dates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-Reshaping.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Reshaping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-joining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Joining</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-data_import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Data Import</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#warm-up" id="toc-warm-up" class="nav-link active" data-scroll-target="#warm-up"><span class="header-section-number">19</span> Warm-up</a>
  <ul class="collapse">
<li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">19.1</span> Exercises</a>
  <ul class="collapse">
<li><a href="#exercise-1-whats-the-problem" id="toc-exercise-1-whats-the-problem" class="nav-link" data-scroll-target="#exercise-1-whats-the-problem">Exercise 1: What’s the problem?</a></li>
  <li><a href="#exercise-2-pivot-longer" id="toc-exercise-2-pivot-longer" class="nav-link" data-scroll-target="#exercise-2-pivot-longer">Exercise 2: Pivot longer</a></li>
  <li><a href="#exercise-3-changing-variable-classes-plotting" id="toc-exercise-3-changing-variable-classes-plotting" class="nav-link" data-scroll-target="#exercise-3-changing-variable-classes-plotting">Exercise 3: Changing variable classes &amp; plotting</a></li>
  <li><a href="#exercise-4-pivot-wider" id="toc-exercise-4-pivot-wider" class="nav-link" data-scroll-target="#exercise-4-pivot-wider">Exercise 4: Pivot wider</a></li>
  <li><a href="#exercise-5-practice-with-billboard-charts" id="toc-exercise-5-practice-with-billboard-charts" class="nav-link" data-scroll-target="#exercise-5-practice-with-billboard-charts">Exercise 5: Practice with Billboard charts</a></li>
  <li><a href="#exercise-6-practice-with-the-daily-show" id="toc-exercise-6-practice-with-the-daily-show" class="nav-link" data-scroll-target="#exercise-6-practice-with-the-daily-show">Exercise 6: Practice with the Daily Show</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ica/quarto-demo.html">In-class Activities</a></li><li class="breadcrumb-item"><a href="../ica/ica-Reshaping.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Reshaping</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Reshaping</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="warm-up" class="level1" data-number="19"><h1 data-number="19">
<span class="header-section-number">19</span> Warm-up</h1>
<p><strong>EXAMPLE 1: warm-up counts and proportions</strong></p>
<p>Recall the <code>penguins</code> we worked with last class:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>penguins <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 344 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): species, island, sex
dbl (5): bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, year

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Tally up the number of male/female penguins by species in 2 ways:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Using count()</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">count</span>(species, sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  species   sex        n
  &lt;chr&gt;     &lt;chr&gt;  &lt;int&gt;
1 Adelie    female    73
2 Adelie    male      73
3 Adelie    &lt;NA&gt;       6
4 Chinstrap female    34
5 Chinstrap male      34
6 Gentoo    female    58
7 Gentoo    male      61
8 Gentoo    &lt;NA&gt;       5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Using group_by() and summarize()</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">summarise</span>(<span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'species'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
# Groups:   species [3]
  species   sex    `n()`
  &lt;chr&gt;     &lt;chr&gt;  &lt;int&gt;
1 Adelie    female    73
2 Adelie    male      73
3 Adelie    &lt;NA&gt;       6
4 Chinstrap female    34
5 Chinstrap male      34
6 Gentoo    female    58
7 Gentoo    male      61
8 Gentoo    &lt;NA&gt;       5</code></pre>
</div>
</div>
<p>Define a new column that includes the <em>proportion</em> or <em>relative frequencies</em> of male/female penguins in each species.</p>
<ul>
<li>We can’t do this by adjusting our <code>count()</code> code, but <em>can</em> adjust the <code>group_by()</code> and <code>summarize()</code> code since it’s still tracking the group categories in the background.</li>
<li>Does the order of <code>species</code> and <code>sex</code> in <code>group_by()</code> matter?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Relative freq</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span> </span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb10-5"><a href="#cb10-5"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'species'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
# Groups:   species [3]
  species   sex        n proportion
  &lt;chr&gt;     &lt;chr&gt;  &lt;int&gt;      &lt;dbl&gt;
1 Adelie    female    73     0.480 
2 Adelie    male      73     0.480 
3 Adelie    &lt;NA&gt;       6     0.0395
4 Chinstrap female    34     0.5   
5 Chinstrap male      34     0.5   
6 Gentoo    female    58     0.468 
7 Gentoo    male      61     0.492 
8 Gentoo    &lt;NA&gt;       5     0.0403</code></pre>
</div>
</div>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 2: New data</strong></p>
<p>What will the following code do? Think about it before running.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>penguin_avg <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">summarize</span>(<span class="at">avg_body_mass =</span> <span class="fu">mean</span>(body_mass_g, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb13-4"><a href="#cb13-4"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'species'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 3: units of observation</strong></p>
<p>To get the information on average body masses, we <em>reshaped</em> our original data.</p>
<ol type="1">
<li>Did the <em>reshaping</em> process change the units of observation?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Units of observation = 6</span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="fu">head</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
  &lt;chr&gt;   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;dbl&gt;       &lt;dbl&gt;
1 Adelie  Torgersen           39.1          18.7               181        3750
2 Adelie  Torgersen           39.5          17.4               186        3800
3 Adelie  Torgersen           40.3          18                 195        3250
4 Adelie  Torgersen           NA            NA                  NA          NA
5 Adelie  Torgersen           36.7          19.3               193        3450
6 Adelie  Torgersen           39.3          20.6               190        3650
# ℹ 2 more variables: sex &lt;chr&gt;, year &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Units of observation = 6</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="fu">head</span>(penguin_avg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   species [3]
  species   sex    avg_body_mass
  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 Adelie    female         3369.
2 Adelie    male           4043.
3 Chinstrap female         3527.
4 Chinstrap male           3939.
5 Gentoo    female         4680.
6 Gentoo    male           5485.</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Did the reshaping process result in any information loss from the original data? Yes, we lost the Island, year, and bill data<br><br><br><br><br>
</li>
</ol>
<p><strong>Reshaping data</strong></p>
<p>There are two general types of reshaped data:</p>
<ul>
<li><p><em>aggregate</em> data<br>
For example, using <code>group_by()</code> with <code>summarize()</code> gains aggregate information about our observations but loses data on individual observations.</p></li>
<li><p><em>raw</em> data, reshaped<br>
We often want to retain all information on individual observations, but need to reshape it in order to perform the task at hand.</p></li>
</ul>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 4: reshape it with your mind</strong></p>
<p>Let’s calculate the <em>difference</em> in average body mass, male vs female, for each species. Since <code>penguin_avg</code> is small, we <em>could</em> do these calculations by hand. But this doesn’t scale up to bigger datasets.</p>
<ul>
<li><p>Sketch out (on paper, in your head, anything) how this data would need to be <em>reshaped</em>, <em>without</em> losing any information, in order to calculate the differences in average body mass using our wrangling verbs. Make it as specific as possible, with column labels, entries, correct numbers, etc.</p></li>
<li><p>Identify the units of observation.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>penguin_avg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   species [3]
  species   sex    avg_body_mass
  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 Adelie    female         3369.
2 Adelie    male           4043.
3 Chinstrap female         3527.
4 Chinstrap male           3939.
5 Gentoo    female         4680.
6 Gentoo    male           5485.</code></pre>
</div>
</div>
<p><br><br><br><br><br></p>
<p><strong>Wider vs Longer formats</strong></p>
<p>Making our data <em>longer</em> or <em>wider</em> reshapes the data, changing the units of observation while retaining <em>all</em> raw information:</p>
<ol type="1">
<li>Make the data <em>longer</em>, i.e.&nbsp;combine values from multiple variables into 1 variable. EXAMPLE: <code>1999</code> and <code>2000</code> represent two years. We want to <em>combine</em> their results into 1 variable without losing any information.</li>
</ol>
<p><img src="https://mac-stat.github.io/images/112/pivot_longer.png" class="img-fluid"></p>
<ol start="2" type="1">
<li>Make the data <em>wider</em>, i.e.&nbsp;spread out the values across new variables. EXAMPLE: <code>cases</code> and <code>pop</code> represent two categories within <code>type</code>. To compare or combine their <code>count</code> outcomes side-by-side, we can <em>separate</em> them into their own variables.</li>
</ol>
<p><img src="https://mac-stat.github.io/images/112/pivot_wider.png" class="img-fluid"></p>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 5: pivot wider</strong></p>
<p>Because it’s a small enough dataset to examine all at once, let’s start with our <code>penguin_avg</code> data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>penguin_avg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   species [3]
  species   sex    avg_body_mass
  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 Adelie    female         3369.
2 Adelie    male           4043.
3 Chinstrap female         3527.
4 Chinstrap male           3939.
5 Gentoo    female         4680.
6 Gentoo    male           5485.</code></pre>
</div>
</div>
<p>With the goal of being able to calculate the <em>difference</em> in average body mass, male vs female, for each species, let’s make the dataset <em>wider</em>. That is, let’s get one row per <code>species</code> with separate columns for the average body mass by <code>sex</code>. Put this code into a chunk and run it:</p>
<p>penguin_avg |&gt; pivot_wider(names_from = sex, values_from = avg_body_mass)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
# Groups:   species [3]
  species   female  male
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 Adelie     3369. 4043.
2 Chinstrap  3527. 3939.
3 Gentoo     4680. 5485.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Pivot Wider">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pivot Wider
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<code>names_from</code> = the variable whose values we want to separate into their own columns, i.e.&nbsp;where we want to get the new column <em>names from</em>
</li>
<li>
<code>values_from</code> = which variable to take the new column <em>values from</em>
</li>
</ul>
</div>
</div>
<p>FOLLOW-UP:</p>
<ul>
<li><p>What are the units of observation? adelie, gentoo, chinstrap</p></li>
<li><p>Did we lose any information when we widened the data? no</p></li>
<li><p>Use the wide data to calculate the difference in average body mass, male vs female, for each species.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass) <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> male <span class="sc">-</span> female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
# Groups:   species [3]
  species   female  male  diff
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Adelie     3369. 4043.  675.
2 Chinstrap  3527. 3939.  412.
3 Gentoo     4680. 5485.  805.</code></pre>
</div>
</div>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 6: Pivot longer</strong></p>
<p>Let’s store our wide data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>penguin_avg_wide <span class="ot">&lt;-</span> penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass)</span>
<span id="cb27-3"><a href="#cb27-3"></a></span>
<span id="cb27-4"><a href="#cb27-4"></a>penguin_avg_wide</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
# Groups:   species [3]
  species   female  male
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 Adelie     3369. 4043.
2 Chinstrap  3527. 3939.
3 Gentoo     4680. 5485.</code></pre>
</div>
</div>
<p>Suppose we wanted to change this data back to a <em>longer</em> format. In general, this happens when some variables (here <code>female</code> and <code>male</code>) represent two categories or values of some <em>broader</em> variable (here <code>sex</code>), and we want to combine them into that 1 variable without losing any information. Let’s <code>pivot_longer()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># We can either communicate which variables we WANT to collect into a single column (female, male)</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>penguin_avg_wide <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(female, male), <span class="at">names_to =</span> <span class="st">"sex"</span>, <span class="at">values_to =</span> <span class="st">"avg_body_mass"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   species [3]
  species   sex    avg_body_mass
  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 Adelie    female         3369.
2 Adelie    male           4043.
3 Chinstrap female         3527.
4 Chinstrap male           3939.
5 Gentoo    female         4680.
6 Gentoo    male           5485.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Or which variable(s) we do NOT want to collect into a single column (sex)</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>penguin_avg_wide <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>species, <span class="at">names_to =</span> <span class="st">"sex"</span>, <span class="at">values_to =</span> <span class="st">"avg_body_mass"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   species [3]
  species   sex    avg_body_mass
  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 Adelie    female         3369.
2 Adelie    male           4043.
3 Chinstrap female         3527.
4 Chinstrap male           3939.
5 Gentoo    female         4680.
6 Gentoo    male           5485.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Pivot Longer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pivot Longer
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<code>cols</code> = the columns (variables) to collect into a single, new variable. we can also specify what variables we <em>don’t</em> want to collect</li>
<li>
<code>names_to</code> = the name of the new variable which will include the <em>names</em> or labels of the collected variables</li>
<li>
<code>values_to</code> = the name of the new variable which will include the <em>values</em> of the collected variables</li>
</ul>
</div>
</div>
<p>FOLLOW-UP:</p>
<ul>
<li><p>What are the units of observation? species and sex</p></li>
<li><p>Did we lose any information when we lengthened the data? no</p></li>
<li><p>Why did we put the variables in quotes “” here but not when we used <code>pivot_wider()</code>? beacuse we are using the name of the column</p></li>
</ul>
<p><br><br><br><br></p>
<p><strong>EXAMPLE 7: Practice</strong></p>
<p>Let’s make up some data on the orders of 2 different customers at 3 different restaurants:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>food <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-2"><a href="#cb33-2"></a>  <span class="at">customer =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb33-3"><a href="#cb33-3"></a>  <span class="at">restaurant =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Shish"</span>, <span class="st">"FrenchMeadow"</span>, <span class="st">"DunnBros"</span>), <span class="dv">2</span>),</span>
<span id="cb33-4"><a href="#cb33-4"></a>  <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"falafel"</span>, <span class="st">"salad"</span>, <span class="st">"coffee"</span>, <span class="st">"baklava"</span>, <span class="st">"pastry"</span>, <span class="st">"tea"</span>)</span>
<span id="cb33-5"><a href="#cb33-5"></a>)</span>
<span id="cb33-6"><a href="#cb33-6"></a>food</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  customer   restaurant   order
1        A        Shish falafel
2        A FrenchMeadow   salad
3        A     DunnBros  coffee
4        B        Shish baklava
5        B FrenchMeadow  pastry
6        B     DunnBros     tea</code></pre>
</div>
</div>
<p>The units of observation in <code>food</code> are customer / restaurant combinations. Wrangle this data so that the units of observation are customers, spreading the restaurants into separate columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>food <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> restaurant, <span class="at">values_from =</span> order)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  customer Shish   FrenchMeadow DunnBros
  &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;        &lt;chr&gt;   
1 A        falafel salad        coffee  
2 B        baklava pastry       tea     </code></pre>
</div>
</div>
<p>Consider 2 more customers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>more_food <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-2"><a href="#cb37-2"></a>  <span class="at">customer =</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"D"</span>),</span>
<span id="cb37-3"><a href="#cb37-3"></a>  <span class="at">Shish =</span> <span class="fu">c</span>(<span class="st">"coffee"</span>, <span class="st">"maza"</span>),</span>
<span id="cb37-4"><a href="#cb37-4"></a>  <span class="at">FrenchMeadow =</span> <span class="fu">c</span>(<span class="st">"soup"</span>, <span class="st">"sandwich"</span>),</span>
<span id="cb37-5"><a href="#cb37-5"></a>  <span class="at">DunnBros =</span> <span class="fu">c</span>(<span class="st">"cookie"</span>, <span class="st">"coffee"</span>)</span>
<span id="cb37-6"><a href="#cb37-6"></a>)</span>
<span id="cb37-7"><a href="#cb37-7"></a>more_food</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  customer  Shish FrenchMeadow DunnBros
1        C coffee         soup   cookie
2        D   maza     sandwich   coffee</code></pre>
</div>
</div>
<p>Wrangle this data so that the 3 restaurant columns are combined into 1, hence the units of observation are customer / restaurant combinations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>more_food <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>customer, <span class="at">names_to =</span> <span class="st">"restaurant"</span>, <span class="at">values_to =</span> <span class="st">"order"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  customer restaurant   order   
  &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;   
1 C        Shish        coffee  
2 C        FrenchMeadow soup    
3 C        DunnBros     cookie  
4 D        Shish        maza    
5 D        FrenchMeadow sandwich
6 D        DunnBros     coffee  </code></pre>
</div>
</div>
<p><br><br><br><br></p>
<section id="exercises" class="level2" data-number="19.1"><h2 data-number="19.1" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">19.1</span> Exercises</h2>
<section id="exercise-1-whats-the-problem" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-1-whats-the-problem">Exercise 1: What’s the problem?</h3>
<p>Consider data on a sleep study in which subjects received only 3 hours of sleep per night. Each day, their reaction time to a stimulus (in ms) was recorded.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>sleep_wide <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://mac-stat.github.io/data/sleep_wide.csv"</span>)</span>
<span id="cb41-2"><a href="#cb41-2"></a></span>
<span id="cb41-3"><a href="#cb41-3"></a><span class="fu">head</span>(sleep_wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Subject  day_0  day_1  day_2  day_3  day_4  day_5  day_6  day_7  day_8  day_9
1     308 249.56 258.70 250.80 321.44 356.85 414.69 382.20 290.15 430.59 466.35
2     309 222.73 205.27 202.98 204.71 207.72 215.96 213.63 217.73 224.30 237.31
3     310 199.05 194.33 234.32 232.84 229.31 220.46 235.42 255.75 261.01 247.52
4     330 321.54 300.40 283.86 285.13 285.80 297.59 280.24 318.26 305.35 354.05
5     331 287.61 285.00 301.82 320.12 316.28 293.32 290.08 334.82 293.75 371.58
6     332 234.86 242.81 272.96 309.77 317.46 310.00 454.16 346.83 330.30 253.86</code></pre>
</div>
</div>
<section id="part-a" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a">Part a</h4>
<p>What are the units of observation in <code>sleep_wide</code>? - subjects</p>
</section><section id="part-b" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b">Part b</h4>
<p>Suppose I ask you to plot each subject’s reaction time (y-axis) vs the number of days of sleep restriction (x-axis). “Sketch” out in words what the first few rows of the data need to look like in order to do this. It might help to think about what you’d need to complete the plotting frame:</p>
<p><code>ggplot(___, aes(y = ___, x = ___, color = ___))</code></p>
<ul>
<li>we would need the days to be the units of observations, so it owuld look like |day_ | subject | performance | 1 | 308 | 249.56</li>
</ul></section><section id="part-c" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-c">Part c</h4>
<p>How can you obtain the dataset you sketched in part b? You would want to use pivot_longer</p>
<ul>
<li>just using <code>sleep_wide</code>
</li>
<li><code>pivot_longer()</code></li>
<li><code>pivot_wider()</code></li>
</ul>
<p><br><br><br><br></p>
</section></section><section id="exercise-2-pivot-longer" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-2-pivot-longer">Exercise 2: Pivot longer</h3>
<p>To plot reaction time by day for each subject, we need to reshape the data into a <strong>long</strong> format where each row represents a subject/day combination. Specifically, we want a dataset with 3 columns and a first few rows that look something like this:</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;">Subject</th>
<th style="text-align: right;">day</th>
<th style="text-align: right;">reaction_time</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">308</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">249.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">308</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">258.70</td>
</tr>
<tr class="odd">
<td style="text-align: right;">308</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">250.80</td>
</tr>
</tbody>
</table>
<section id="part-a-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a-1">Part a</h4>
<p>Use <code>pivot_longer()</code> to create the long-format dataset above. Show the first 3 lines (<code>head(3)</code>), which should be <em>similar</em> to those above. Follow-up: Thinking forward to plotting reaction time vs day for each subject, what would you like to fix / change about this dataset?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="co"># For cols, try 2 appproaches: using - and starts_with</span></span>
<span id="cb43-2"><a href="#cb43-2"></a> sleep_wide <span class="sc">|&gt;</span> </span>
<span id="cb43-3"><a href="#cb43-3"></a>   <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject, <span class="at">names_to =</span> <span class="st">"day"</span>, <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 3
   Subject day   reaction_time
     &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
 1     308 day_0          250.
 2     308 day_1          259.
 3     308 day_2          251.
 4     308 day_3          321.
 5     308 day_4          357.
 6     308 day_5          415.
 7     308 day_6          382.
 8     308 day_7          290.
 9     308 day_8          431.
10     308 day_9          466.
# ℹ 170 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>sleep_wide <span class="sc">|&gt;</span> <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"day"</span>), <span class="at">names_to =</span> <span class="st">"day"</span>, <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 3
   Subject day   reaction_time
     &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
 1     308 day_0          250.
 2     308 day_1          259.
 3     308 day_2          251.
 4     308 day_3          321.
 5     308 day_4          357.
 6     308 day_5          415.
 7     308 day_6          382.
 8     308 day_7          290.
 9     308 day_8          431.
10     308 day_9          466.
# ℹ 170 more rows</code></pre>
</div>
</div>
</section><section id="part-b-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b-1">Part b</h4>
<p>Run this chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>sleep_long <span class="ot">&lt;-</span> sleep_wide <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject,</span>
<span id="cb47-3"><a href="#cb47-3"></a>               <span class="at">names_to =</span> <span class="st">"day"</span>,</span>
<span id="cb47-4"><a href="#cb47-4"></a>               <span class="at">names_prefix =</span> <span class="st">"day_"</span>,</span>
<span id="cb47-5"><a href="#cb47-5"></a>               <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span>
<span id="cb47-6"><a href="#cb47-6"></a></span>
<span id="cb47-7"><a href="#cb47-7"></a><span class="fu">head</span>(sleep_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Subject day   reaction_time
    &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
1     308 0              250.
2     308 1              259.
3     308 2              251.
4     308 3              321.
5     308 4              357.
6     308 5              415.</code></pre>
</div>
</div>
<p>Follow-up:</p>
<ul>
<li>Besides putting each argument on a different line for readability and storing the results, what changed in the code? day_ was removed from the day column</li>
<li>How did this impact how the values are recorded in the <code>day</code> column?
<ul>
<li>it got rid of the day_ prefix in the vaules of the column</li>
</ul>
</li>
</ul></section><section id="part-c-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-c-1">Part c</h4>
<p>Using <code>sleep_long</code>, construct a line plot of reaction time vs day for each subject. This will look goofy no matter what you do. Why? HINT: look back at <code>head(sleep_long)</code>. What class or type of variables are <code>Subject</code> and <code>day</code>? What do we <em>want</em> them to be? (<code>Subject</code> is integer and <code>day</code> is character but we want <code>subject</code> as a factor and <code>day</code> as a numeric value )</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br><br><br><br></p>
</section></section><section id="exercise-3-changing-variable-classes-plotting" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-3-changing-variable-classes-plotting">Exercise 3: Changing variable classes &amp; plotting</h3>
<p>Let’s finalize <code>sleep_long</code> by <em>mutating</em> the <code>Subject</code> variable to be a <code>factor</code> (categorical) and the <code>day</code> variable to be <code>numeric</code> (quantitative). Take note of the <code>mutate()</code> code! You’ll use this type of code a lot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>sleep_long <span class="ot">&lt;-</span> sleep_wide <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject,</span>
<span id="cb50-3"><a href="#cb50-3"></a>               <span class="at">names_to =</span> <span class="st">"day"</span>,</span>
<span id="cb50-4"><a href="#cb50-4"></a>               <span class="at">names_prefix =</span> <span class="st">"day_"</span>,</span>
<span id="cb50-5"><a href="#cb50-5"></a>               <span class="at">values_to =</span> <span class="st">"reaction_time"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb50-6"><a href="#cb50-6"></a>  <span class="fu">mutate</span>(<span class="at">Subject =</span> <span class="fu">as.factor</span>(Subject), <span class="at">day =</span> <span class="fu">as.numeric</span>(day))</span>
<span id="cb50-7"><a href="#cb50-7"></a></span>
<span id="cb50-8"><a href="#cb50-8"></a><span class="co"># Check it out</span></span>
<span id="cb50-9"><a href="#cb50-9"></a><span class="co"># Same data, different class</span></span>
<span id="cb50-10"><a href="#cb50-10"></a><span class="fu">head</span>(sleep_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Subject   day reaction_time
  &lt;fct&gt;   &lt;dbl&gt;         &lt;dbl&gt;
1 308         0          250.
2 308         1          259.
3 308         2          251.
4 308         3          321.
5 308         4          357.
6 308         5          415.</code></pre>
</div>
</div>
<section id="part-a-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a-2">Part a</h4>
<p><em>Now</em> make some plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="co"># Make a line plot of reaction time by day for each subject</span></span>
<span id="cb52-2"><a href="#cb52-2"></a><span class="co"># Put these all on the same frame</span></span>
<span id="cb52-3"><a href="#cb52-3"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time, <span class="at">color =</span> Subject)) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="co"># Make a line plot of reaction time by day for each subject</span></span>
<span id="cb53-2"><a href="#cb53-2"></a><span class="co"># Put these all on separate frames (one per subject)</span></span>
<span id="cb53-3"><a href="#cb53-3"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Subject)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="part-b-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b-2">Part b</h4>
<p>Summarize what you learned from the plots. For example:</p>
<ul>
<li>What’s the general relationship between reaction time and sleep? generally the later the day in the study related to slower reaction times</li>
<li>Is this the same for everybody? What differs? No this was not the same for some people it got faster at some points but then when down again and for others it contiunally got slower.</li>
</ul>
<p><br><br><br><br></p>
</section></section><section id="exercise-4-pivot-wider" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-4-pivot-wider">Exercise 4: Pivot wider</h3>
<p>Make the data <em>wide</em> again, with each day becoming its own column.</p>
<section id="part-a-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a-3">Part a</h4>
<p>Adjust the code below. What don’t you like about the column labels?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a> sleep_long <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2"></a>   <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> day, <span class="at">values_from =</span> reaction_time) <span class="sc">|&gt;</span> </span>
<span id="cb54-3"><a href="#cb54-3"></a>   <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  Subject   `0`   `1`   `2`   `3`   `4`   `5`   `6`   `7`   `8`   `9`
  &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 308      250.  259.  251.  321.  357.  415.  382.  290.  431.  466.
2 309      223.  205.  203.  205.  208.  216.  214.  218.  224.  237.
3 310      199.  194.  234.  233.  229.  220.  235.  256.  261.  248.
4 330      322.  300.  284.  285.  286.  298.  280.  318.  305.  354.
5 331      288.  285   302.  320.  316.  293.  290.  335.  294.  372.
6 332      235.  243.  273.  310.  317.  310   454.  347.  330.  254.</code></pre>
</div>
</div>
</section><section id="part-b-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b-3">Part b</h4>
<p>Using your intuition, adjust your code from part a to name the reaction time columns “day_0”, “day_1”, etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a> sleep_long <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2"></a>   <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> day, <span class="at">values_from =</span> reaction_time, <span class="at">names_prefix =</span> <span class="st">"day_"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb56-3"><a href="#cb56-3"></a>   <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  Subject day_0 day_1 day_2 day_3 day_4 day_5 day_6 day_7 day_8 day_9
  &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 308      250.  259.  251.  321.  357.  415.  382.  290.  431.  466.
2 309      223.  205.  203.  205.  208.  216.  214.  218.  224.  237.
3 310      199.  194.  234.  233.  229.  220.  235.  256.  261.  248.
4 330      322.  300.  284.  285.  286.  298.  280.  318.  305.  354.
5 331      288.  285   302.  320.  316.  293.  290.  335.  294.  372.
6 332      235.  243.  273.  310.  317.  310   454.  347.  330.  254.</code></pre>
</div>
</div>
<p><br><br><br><br></p>
</section></section><section id="exercise-5-practice-with-billboard-charts" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-5-practice-with-billboard-charts">Exercise 5: Practice with Billboard charts</h3>
<p>Load data on songs that hit the <code>billboard</code> charts around the year 2000. Included for each song is the <code>artist</code> name, <code>track</code> name, the date it hit the charts (<code>date.enter</code>), and <code>wk</code>-related variables that indicate rankings in each subsequent week on the charts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="co"># Load data</span></span>
<span id="cb58-2"><a href="#cb58-2"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb58-3"><a href="#cb58-3"></a><span class="fu">data</span>(<span class="st">"billboard"</span>)</span>
<span id="cb58-4"><a href="#cb58-4"></a></span>
<span id="cb58-5"><a href="#cb58-5"></a><span class="co"># Check it out</span></span>
<span id="cb58-6"><a href="#cb58-6"></a><span class="fu">head</span>(billboard)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 79
  artist      track date.entered   wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8
  &lt;chr&gt;       &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 2 Pac       Baby… 2000-02-26      87    82    72    77    87    94    99    NA
2 2Ge+her     The … 2000-09-02      91    87    92    NA    NA    NA    NA    NA
3 3 Doors Do… Kryp… 2000-04-08      81    70    68    67    66    57    54    53
4 3 Doors Do… Loser 2000-10-21      76    76    72    69    67    65    55    59
5 504 Boyz    Wobb… 2000-04-15      57    34    25    17    17    31    36    49
6 98^0        Give… 2000-08-19      51    39    34    26    26    19     2     2
# ℹ 68 more variables: wk9 &lt;dbl&gt;, wk10 &lt;dbl&gt;, wk11 &lt;dbl&gt;, wk12 &lt;dbl&gt;,
#   wk13 &lt;dbl&gt;, wk14 &lt;dbl&gt;, wk15 &lt;dbl&gt;, wk16 &lt;dbl&gt;, wk17 &lt;dbl&gt;, wk18 &lt;dbl&gt;,
#   wk19 &lt;dbl&gt;, wk20 &lt;dbl&gt;, wk21 &lt;dbl&gt;, wk22 &lt;dbl&gt;, wk23 &lt;dbl&gt;, wk24 &lt;dbl&gt;,
#   wk25 &lt;dbl&gt;, wk26 &lt;dbl&gt;, wk27 &lt;dbl&gt;, wk28 &lt;dbl&gt;, wk29 &lt;dbl&gt;, wk30 &lt;dbl&gt;,
#   wk31 &lt;dbl&gt;, wk32 &lt;dbl&gt;, wk33 &lt;dbl&gt;, wk34 &lt;dbl&gt;, wk35 &lt;dbl&gt;, wk36 &lt;dbl&gt;,
#   wk37 &lt;dbl&gt;, wk38 &lt;dbl&gt;, wk39 &lt;dbl&gt;, wk40 &lt;dbl&gt;, wk41 &lt;dbl&gt;, wk42 &lt;dbl&gt;,
#   wk43 &lt;dbl&gt;, wk44 &lt;dbl&gt;, wk45 &lt;dbl&gt;, wk46 &lt;dbl&gt;, wk47 &lt;dbl&gt;, wk48 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>In using this data, you’ll need to determine if and when the data needs to be reshaped for the task at hand.</p>
<section id="part-a-4" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a-4">Part a</h4>
<p>Construct and summarize a plot of how a song’s Billboard ranking its 2nd week on the chart (y-axis) is related to its ranking the 1st week on the charts (x-axis). Add a reference line <code>geom_abline(intercept = 0, slope = 1)</code>. Songs <em>above</em> this line <em>improved</em> their rankings from the 1st to 2nd week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">ggplot</span>(billboard, <span class="fu">aes</span>(<span class="at">x =</span> wk1, <span class="at">y =</span> wk2)) <span class="sc">+</span> </span>
<span id="cb60-2"><a href="#cb60-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="part-b-4" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b-4">Part b</h4>
<p>Use your wrangling tools to identify <em>which</em> songs are those above the line in Part a, i.e.&nbsp;with rankgings that went up from week 1 to week 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>billboard <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a href="#cb62-2"></a>  <span class="fu">filter</span>(wk2 <span class="sc">&gt;</span> wk1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 79
  artist      track date.entered   wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8
  &lt;chr&gt;       &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Carey, Mar… Cryb… 2000-06-24      28    34    48    62    77    90    95    NA
2 Clark, Ter… A Li… 2000-12-16      75    82    88    96    99    99    NA    NA
3 Diffie, Joe The … 2000-01-01      98   100   100    90    93    94    NA    NA
4 Hart, Beth  L.A.… 1999-11-27      99   100    98    99    99    99    98    90
5 Jay-Z       Hey … 2000-08-12      98   100    98    94    83    83    80    78
6 Lil' Zane   Call… 2000-07-29      83    89    57    40    34    21    33    46
7 Pearl Jam   Noth… 2000-05-13      49    70    84    89    93    91    NA    NA
# ℹ 68 more variables: wk9 &lt;dbl&gt;, wk10 &lt;dbl&gt;, wk11 &lt;dbl&gt;, wk12 &lt;dbl&gt;,
#   wk13 &lt;dbl&gt;, wk14 &lt;dbl&gt;, wk15 &lt;dbl&gt;, wk16 &lt;dbl&gt;, wk17 &lt;dbl&gt;, wk18 &lt;dbl&gt;,
#   wk19 &lt;dbl&gt;, wk20 &lt;dbl&gt;, wk21 &lt;dbl&gt;, wk22 &lt;dbl&gt;, wk23 &lt;dbl&gt;, wk24 &lt;dbl&gt;,
#   wk25 &lt;dbl&gt;, wk26 &lt;dbl&gt;, wk27 &lt;dbl&gt;, wk28 &lt;dbl&gt;, wk29 &lt;dbl&gt;, wk30 &lt;dbl&gt;,
#   wk31 &lt;dbl&gt;, wk32 &lt;dbl&gt;, wk33 &lt;dbl&gt;, wk34 &lt;dbl&gt;, wk35 &lt;dbl&gt;, wk36 &lt;dbl&gt;,
#   wk37 &lt;dbl&gt;, wk38 &lt;dbl&gt;, wk39 &lt;dbl&gt;, wk40 &lt;dbl&gt;, wk41 &lt;dbl&gt;, wk42 &lt;dbl&gt;,
#   wk43 &lt;dbl&gt;, wk44 &lt;dbl&gt;, wk45 &lt;dbl&gt;, wk46 &lt;dbl&gt;, wk47 &lt;dbl&gt;, wk48 &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section><section id="part-c-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-c-2">Part c</h4>
<p>Define a new dataset, <code>nov_1999</code>, which:</p>
<ul>
<li>only includes data on songs that entered the Billboard charts on November 6, 1999</li>
<li>keeps all variables <em>except</em> <code>track</code> and <code>date.entered</code>. HINT: How can you avoid writing out all the variable names you want to keep?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="co"># Define nov_1999</span></span>
<span id="cb64-2"><a href="#cb64-2"></a>nov_1999 <span class="ot">&lt;-</span> billboard <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="#cb64-3"></a>  <span class="fu">filter</span>(date.entered <span class="sc">==</span> <span class="st">"1999-11-06"</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="#cb64-4"></a>  <span class="fu">select</span>(<span class="sc">-</span>track, <span class="sc">-</span>date.entered)</span>
<span id="cb64-5"><a href="#cb64-5"></a></span>
<span id="cb64-6"><a href="#cb64-6"></a><span class="co"># Confirm that nov_1999 has 2 rows (songs) and 77 columns</span></span>
<span id="cb64-7"><a href="#cb64-7"></a><span class="fu">dim</span>(nov_1999)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2 77</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="fu">head</span>(nov_1999)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 77
  artist   wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8   wk9  wk10  wk11  wk12
  &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Count…    84    70    66    60    46    37    35    35    35    32    29    29
2 Hill,…    81    68    62    51    42    35    28    28    28    43    30    23
# ℹ 64 more variables: wk13 &lt;dbl&gt;, wk14 &lt;dbl&gt;, wk15 &lt;dbl&gt;, wk16 &lt;dbl&gt;,
#   wk17 &lt;dbl&gt;, wk18 &lt;dbl&gt;, wk19 &lt;dbl&gt;, wk20 &lt;dbl&gt;, wk21 &lt;dbl&gt;, wk22 &lt;dbl&gt;,
#   wk23 &lt;dbl&gt;, wk24 &lt;dbl&gt;, wk25 &lt;dbl&gt;, wk26 &lt;dbl&gt;, wk27 &lt;dbl&gt;, wk28 &lt;dbl&gt;,
#   wk29 &lt;dbl&gt;, wk30 &lt;dbl&gt;, wk31 &lt;dbl&gt;, wk32 &lt;dbl&gt;, wk33 &lt;dbl&gt;, wk34 &lt;dbl&gt;,
#   wk35 &lt;dbl&gt;, wk36 &lt;dbl&gt;, wk37 &lt;dbl&gt;, wk38 &lt;dbl&gt;, wk39 &lt;dbl&gt;, wk40 &lt;dbl&gt;,
#   wk41 &lt;dbl&gt;, wk42 &lt;dbl&gt;, wk43 &lt;dbl&gt;, wk44 &lt;dbl&gt;, wk45 &lt;dbl&gt;, wk46 &lt;dbl&gt;,
#   wk47 &lt;dbl&gt;, wk48 &lt;dbl&gt;, wk49 &lt;dbl&gt;, wk50 &lt;dbl&gt;, wk51 &lt;dbl&gt;, wk52 &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section><section id="part-d" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-d">Part d</h4>
<p>Create and discuss a visualization of the rankings (y-axis) over time (x-axis) for the 2 songs in <code>nov_1999</code>. There are hints below (if you scroll), but you’re encouraged to play around and use as few hints as possible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a>nov_1999 <span class="sc">|&gt;</span> </span>
<span id="cb68-2"><a href="#cb68-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>artist, <span class="at">names_to =</span> <span class="st">"week"</span>, <span class="at">names_prefix =</span> <span class="st">"wk"</span>, <span class="at">values_to =</span> <span class="st">"rank"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb68-3"><a href="#cb68-3"></a>  <span class="fu">mutate</span>(<span class="at">week =</span> <span class="fu">as.numeric</span>(week)) <span class="sc">|&gt;</span> </span>
<span id="cb68-4"><a href="#cb68-4"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> rank, <span class="at">x =</span> week, <span class="at">color =</span> artist)) <span class="sc">+</span> </span>
<span id="cb68-5"><a href="#cb68-5"></a>    <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 79 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Hints:</p>
<ul>
<li>Should you first pivot wider or longer?</li>
<li>Once you pivot, the week number is turned into a character variable. How can you change it to a number?</li>
</ul>
<p><br><br><br><br></p>
</section></section><section id="exercise-6-practice-with-the-daily-show" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="exercise-6-practice-with-the-daily-show">Exercise 6: Practice with the Daily Show</h3>
<p>The data associated with <a href="https://fivethirtyeight.com/datalab/every-guest-jon-stewart-ever-had-on-the-daily-show/">this article</a> is available in the <code>fivethirtyeight</code> package, and is loaded into <code>daily</code> below. It includes a list of every guest to ever appear on Jon Stewart’s The Daily Show, a “late-night talk and satirical news” program (per Wikipedia). Check out the dataset and note that when multiple people appeared together, each person receives their own line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="fu">library</span>(fivethirtyeight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Some larger datasets need to be installed separately, like senators and
house_district_forecast. To install these, we recommend you install the
fivethirtyeightdata package by running:
install.packages('fivethirtyeightdata', repos =
'https://fivethirtyeightdata.github.io/drat/', type = 'source')</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a><span class="fu">data</span>(<span class="st">"daily_show_guests"</span>)</span>
<span id="cb72-2"><a href="#cb72-2"></a>daily <span class="ot">&lt;-</span> daily_show_guests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In analyzing this data, you’ll need to determine if and when the data needs to be reshaped.</p>
<section id="part-a-5" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-a-5">Part a</h4>
<p>Identify the 15 guests that appeared the most. (This isn’t a very diverse guest list!)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a>daily <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2"></a>  <span class="fu">count</span>(raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="#cb73-3"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb73-4"><a href="#cb73-4"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 2
   raw_guest_list        n
   &lt;chr&gt;             &lt;int&gt;
 1 Fareed Zakaria       19
 2 Denis Leary          17
 3 Brian Williams       16
 4 Paul Rudd            13
 5 Ricky Gervais        13
 6 Tom Brokaw           12
 7 Bill O'Reilly        10
 8 Reza Aslan           10
 9 Richard Lewis        10
10 Will Ferrell         10
11 Sarah Vowell          9
12 Adam Sandler          8
13 Ben Affleck           8
14 Louis C.K.            8
15 Maggie Gyllenhaal     8</code></pre>
</div>
</div>
</section><section id="part-b-5" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-b-5">Part b</h4>
<p>CHALLENGE: Create the following data set containing 19 columns:</p>
<ul>
<li>The first column should have the 15 guests with the highest number of total appearances on the show, listed in descending order of number of appearances.</li>
<li>17 columns should show the number of appearances of the corresponding guest in each year from 1999 to 2015 (one per column).</li>
<li>Another column should show the total number of appearances for the corresponding guest over the entire duration of the show.</li>
</ul>
<p>There are hints below (if you scroll), but you’re encouraged to play around and use as few hints as possible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a>wide_daily_guest <span class="ot">&lt;-</span> daily <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="#cb75-2"></a>  <span class="fu">count</span>(year, raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb75-3"><a href="#cb75-3"></a>  <span class="fu">group_by</span>(raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb75-4"><a href="#cb75-4"></a>  <span class="fu">mutate</span>(<span class="at">total =</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb75-5"><a href="#cb75-5"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> year, <span class="at">values_from =</span> n, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb75-6"><a href="#cb75-6"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total))</span>
<span id="cb75-7"><a href="#cb75-7"></a>  </span>
<span id="cb75-8"><a href="#cb75-8"></a>  <span class="fu">head</span>(wide_daily_guest, <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 19
# Groups:   raw_guest_list [15]
   raw_guest_list  total `1999` `2000` `2001` `2002` `2003` `2004` `2005` `2006`
   &lt;chr&gt;           &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
 1 Fareed Zakaria     19      0      0      1      0      1      2      2      2
 2 Denis Leary        17      1      0      1      2      1      0      0      1
 3 Brian Williams     16      0      0      0      0      1      1      2      1
 4 Paul Rudd          13      1      0      1      1      1      1      1      0
 5 Ricky Gervais      13      0      0      0      0      0      0      1      2
 6 Tom Brokaw         12      0      0      0      1      0      2      1      0
 7 Richard Lewis      10      1      0      2      2      1      1      0      0
 8 Will Ferrell       10      0      1      1      0      1      1      1      1
 9 Bill O'Reilly      10      0      0      1      1      0      1      1      0
10 Reza Aslan         10      0      0      0      0      0      0      1      2
11 Sarah Vowell        9      0      0      0      1      0      1      1      1
12 Adam Sandler        8      1      2      0      1      0      0      0      1
13 Ben Affleck         8      0      0      0      0      2      0      0      1
14 Maggie Gyllenh…     8      0      0      0      0      1      0      1      1
15 Louis C.K.          8      0      0      0      0      0      0      0      1
# ℹ 9 more variables: `2007` &lt;int&gt;, `2008` &lt;int&gt;, `2009` &lt;int&gt;, `2010` &lt;int&gt;,
#   `2011` &lt;int&gt;, `2012` &lt;int&gt;, `2013` &lt;int&gt;, `2014` &lt;int&gt;, `2015` &lt;int&gt;</code></pre>
</div>
</div>
<p>HINTS: There are lots of ways to do this. You don’t necessarily need all of these hints.</p>
<ul>
<li>First obtain the number of times a guest appears each year.</li>
<li>To this, add a new column which includes the total number of times a guest appears across all years.</li>
<li>Pivot (longer or wider?). When you do, use <code>values_fill = 0</code> to replace NA values with 0.</li>
<li>Arrange, then and keep the top 15.</li>
</ul></section><section id="part-c-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="part-c-3">Part c</h4>
<p>Let’s recreate the first figure from <a href="https://fivethirtyeight.com/datalab/every-guest-jon-stewart-ever-had-on-the-daily-show/">the article</a>. This groups all guests into 3 broader occupational categories. However, our current data has 18 categories:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a>daily <span class="sc">|&gt;</span> </span>
<span id="cb77-2"><a href="#cb77-2"></a>  <span class="fu">count</span>(group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
   group              n
   &lt;chr&gt;          &lt;int&gt;
 1 Academic         103
 2 Acting           930
 3 Advocacy          24
 4 Athletics         52
 5 Business          25
 6 Clergy             8
 7 Comedy           150
 8 Consultant        18
 9 Government        40
10 Media            751
11 Military          16
12 Misc              45
13 Musician         123
14 Political Aide    36
15 Politician       308
16 Science           28
17 media              5
18 &lt;NA&gt;              31</code></pre>
</div>
</div>
<p>Let’s define a new dataset that includes a new variable, <code>broad_group</code>, that buckets these 18 categories into the 3 bigger ones used in the article. And get rid of any rows missing information on <code>broad_group</code>. You’ll learn the code soon! For now, just run this chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a>plot_data <span class="ot">&lt;-</span> daily <span class="sc">|&gt;</span> </span>
<span id="cb79-2"><a href="#cb79-2"></a>  <span class="fu">mutate</span>(<span class="at">broad_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb79-3"><a href="#cb79-3"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Acting"</span>, <span class="st">"Athletics"</span>, <span class="st">"Comedy"</span>, <span class="st">"Musician"</span>) <span class="sc">~</span> <span class="st">"Acting, Comedy &amp; Music"</span>,</span>
<span id="cb79-4"><a href="#cb79-4"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Media"</span>, <span class="st">"media"</span>, <span class="st">"Science"</span>, <span class="st">"Academic"</span>, <span class="st">"Consultant"</span>, <span class="st">"Clergy"</span>) <span class="sc">~</span> <span class="st">"Media"</span>,</span>
<span id="cb79-5"><a href="#cb79-5"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Politician"</span>, <span class="st">"Political Aide"</span>, <span class="st">"Government"</span>, <span class="st">"Military"</span>, <span class="st">"Business"</span>, <span class="st">"Advocacy"</span>) <span class="sc">~</span> <span class="st">"Government and Politics"</span>,</span>
<span id="cb79-6"><a href="#cb79-6"></a>    <span class="at">.default =</span> <span class="cn">NA</span></span>
<span id="cb79-7"><a href="#cb79-7"></a>  )) <span class="sc">|&gt;</span> </span>
<span id="cb79-8"><a href="#cb79-8"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(broad_group))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, using the <code>broad_group</code> variable in <code>plot_data</code>, recreate the graphic from the article, with three different lines showing the fraction of guests in each group over time. Note: You’ll have to wrangle the data first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1"></a>plot_data <span class="sc">|&gt;</span></span>
<span id="cb80-2"><a href="#cb80-2"></a>  <span class="fu">group_by</span>(year, broad_group) <span class="sc">|&gt;</span></span>
<span id="cb80-3"><a href="#cb80-3"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb80-4"><a href="#cb80-4"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb80-5"><a href="#cb80-5"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> freq, <span class="at">color =</span> broad_group)) <span class="sc">+</span></span>
<span id="cb80-6"><a href="#cb80-6"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-Reshaping_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br><br><br><br></p>


<!-- -->

</section></section></section></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Gregory Belenky, Nancy J. Wesensten, David R. Thorne, Maria L. Thomas, Helen C. Sing, Daniel P. Redmond, Michael B. Russo and Thomas J. Balkin (2003) Patterns of performance degradation and restoration during sleep restriction and subsequent recovery: a sleep dose-response study. Journal of Sleep Research 12, 1–12.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../ica/Dates.html" class="pagination-link" aria-label="Dates">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Dates</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../ica/ica-joining.html" class="pagination-link" aria-label="Joining">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Joining</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb82" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb82-1"><a href="#cb82-1"></a><span class="co">---</span></span>
<span id="cb82-2"><a href="#cb82-2"></a><span class="an">title:</span><span class="co"> "Reshaping"</span></span>
<span id="cb82-3"><a href="#cb82-3"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb82-4"><a href="#cb82-4"></a><span class="co">---</span></span>
<span id="cb82-5"><a href="#cb82-5"></a></span>
<span id="cb82-6"><a href="#cb82-6"></a><span class="fu"># Warm-up</span></span>
<span id="cb82-7"><a href="#cb82-7"></a></span>
<span id="cb82-8"><a href="#cb82-8"></a>**EXAMPLE 1: warm-up counts and proportions**</span>
<span id="cb82-9"><a href="#cb82-9"></a></span>
<span id="cb82-10"><a href="#cb82-10"></a>Recall the <span class="in">`penguins`</span> we worked with last class:</span>
<span id="cb82-11"><a href="#cb82-11"></a></span>
<span id="cb82-14"><a href="#cb82-14"></a><span class="in">```{r}</span></span>
<span id="cb82-15"><a href="#cb82-15"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb82-16"><a href="#cb82-16"></a>penguins <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv'</span>)</span>
<span id="cb82-17"><a href="#cb82-17"></a><span class="in">```</span></span>
<span id="cb82-18"><a href="#cb82-18"></a></span>
<span id="cb82-19"><a href="#cb82-19"></a>Tally up the number of male/female penguins by species in 2 ways:</span>
<span id="cb82-20"><a href="#cb82-20"></a></span>
<span id="cb82-23"><a href="#cb82-23"></a><span class="in">```{r}</span></span>
<span id="cb82-24"><a href="#cb82-24"></a><span class="co"># Using count()</span></span>
<span id="cb82-25"><a href="#cb82-25"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb82-26"><a href="#cb82-26"></a>  <span class="fu">count</span>(species, sex)</span>
<span id="cb82-27"><a href="#cb82-27"></a></span>
<span id="cb82-28"><a href="#cb82-28"></a><span class="co"># Using group_by() and summarize()</span></span>
<span id="cb82-29"><a href="#cb82-29"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb82-30"><a href="#cb82-30"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span></span>
<span id="cb82-31"><a href="#cb82-31"></a>  <span class="fu">summarise</span>(<span class="fu">n</span>())</span>
<span id="cb82-32"><a href="#cb82-32"></a></span>
<span id="cb82-33"><a href="#cb82-33"></a><span class="in">```</span></span>
<span id="cb82-34"><a href="#cb82-34"></a></span>
<span id="cb82-35"><a href="#cb82-35"></a>Define a new column that includes the *proportion* or *relative frequencies* of male/female penguins in each species.</span>
<span id="cb82-36"><a href="#cb82-36"></a></span>
<span id="cb82-37"><a href="#cb82-37"></a><span class="ss">-   </span>We can't do this by adjusting our <span class="in">`count()`</span> code, but *can* adjust the <span class="in">`group_by()`</span> and <span class="in">`summarize()`</span> code since it's still tracking the group categories in the background.</span>
<span id="cb82-38"><a href="#cb82-38"></a><span class="ss">-   </span>Does the order of <span class="in">`species`</span> and <span class="in">`sex`</span> in <span class="in">`group_by()`</span> matter?</span>
<span id="cb82-39"><a href="#cb82-39"></a></span>
<span id="cb82-42"><a href="#cb82-42"></a><span class="in">```{r}</span></span>
<span id="cb82-43"><a href="#cb82-43"></a><span class="co"># Relative freq</span></span>
<span id="cb82-44"><a href="#cb82-44"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb82-45"><a href="#cb82-45"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span> </span>
<span id="cb82-46"><a href="#cb82-46"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb82-47"><a href="#cb82-47"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb82-48"><a href="#cb82-48"></a><span class="in">```</span></span>
<span id="cb82-49"><a href="#cb82-49"></a></span>
<span id="cb82-50"><a href="#cb82-50"></a>\</span>
<span id="cb82-51"><a href="#cb82-51"></a>\</span>
<span id="cb82-52"><a href="#cb82-52"></a>\</span>
<span id="cb82-53"><a href="#cb82-53"></a>\</span>
<span id="cb82-54"><a href="#cb82-54"></a></span>
<span id="cb82-55"><a href="#cb82-55"></a>**EXAMPLE 2: New data**</span>
<span id="cb82-56"><a href="#cb82-56"></a></span>
<span id="cb82-57"><a href="#cb82-57"></a>What will the following code do? Think about it before running.</span>
<span id="cb82-58"><a href="#cb82-58"></a></span>
<span id="cb82-61"><a href="#cb82-61"></a><span class="in">```{r}</span></span>
<span id="cb82-62"><a href="#cb82-62"></a>penguin_avg <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span> </span>
<span id="cb82-63"><a href="#cb82-63"></a>  <span class="fu">group_by</span>(species, sex) <span class="sc">|&gt;</span> </span>
<span id="cb82-64"><a href="#cb82-64"></a>  <span class="fu">summarize</span>(<span class="at">avg_body_mass =</span> <span class="fu">mean</span>(body_mass_g, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb82-65"><a href="#cb82-65"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb82-66"><a href="#cb82-66"></a><span class="in">```</span></span>
<span id="cb82-67"><a href="#cb82-67"></a></span>
<span id="cb82-68"><a href="#cb82-68"></a>\</span>
<span id="cb82-69"><a href="#cb82-69"></a>\</span>
<span id="cb82-70"><a href="#cb82-70"></a>\</span>
<span id="cb82-71"><a href="#cb82-71"></a>\</span>
<span id="cb82-72"><a href="#cb82-72"></a></span>
<span id="cb82-73"><a href="#cb82-73"></a>**EXAMPLE 3: units of observation**</span>
<span id="cb82-74"><a href="#cb82-74"></a></span>
<span id="cb82-75"><a href="#cb82-75"></a>To get the information on average body masses, we *reshaped* our original data.</span>
<span id="cb82-76"><a href="#cb82-76"></a></span>
<span id="cb82-77"><a href="#cb82-77"></a><span class="ss">1.  </span>Did the *reshaping* process change the units of observation?</span>
<span id="cb82-78"><a href="#cb82-78"></a></span>
<span id="cb82-81"><a href="#cb82-81"></a><span class="in">```{r}</span></span>
<span id="cb82-82"><a href="#cb82-82"></a><span class="co"># Units of observation = 6</span></span>
<span id="cb82-83"><a href="#cb82-83"></a><span class="fu">head</span>(penguins)</span>
<span id="cb82-84"><a href="#cb82-84"></a></span>
<span id="cb82-85"><a href="#cb82-85"></a><span class="co"># Units of observation = 6</span></span>
<span id="cb82-86"><a href="#cb82-86"></a><span class="fu">head</span>(penguin_avg)</span>
<span id="cb82-87"><a href="#cb82-87"></a><span class="in">```</span></span>
<span id="cb82-88"><a href="#cb82-88"></a></span>
<span id="cb82-89"><a href="#cb82-89"></a><span class="ss">2.  </span>Did the reshaping process result in any information loss from the original data?</span>
<span id="cb82-90"><a href="#cb82-90"></a>Yes, we lost the Island, year, and bill data</span>
<span id="cb82-91"><a href="#cb82-91"></a>\</span>
<span id="cb82-92"><a href="#cb82-92"></a>\</span>
<span id="cb82-93"><a href="#cb82-93"></a>\</span>
<span id="cb82-94"><a href="#cb82-94"></a>\</span>
<span id="cb82-95"><a href="#cb82-95"></a>\</span>
<span id="cb82-96"><a href="#cb82-96"></a></span>
<span id="cb82-97"><a href="#cb82-97"></a>**Reshaping data**</span>
<span id="cb82-98"><a href="#cb82-98"></a></span>
<span id="cb82-99"><a href="#cb82-99"></a>There are two general types of reshaped data:</span>
<span id="cb82-100"><a href="#cb82-100"></a></span>
<span id="cb82-101"><a href="#cb82-101"></a><span class="ss">-   </span>*aggregate* data\</span>
<span id="cb82-102"><a href="#cb82-102"></a>    For example, using <span class="in">`group_by()`</span> with <span class="in">`summarize()`</span> gains aggregate information about our observations but loses data on individual observations.</span>
<span id="cb82-103"><a href="#cb82-103"></a></span>
<span id="cb82-104"><a href="#cb82-104"></a><span class="ss">-   </span>*raw* data, reshaped\</span>
<span id="cb82-105"><a href="#cb82-105"></a>    We often want to retain all information on individual observations, but need to reshape it in order to perform the task at hand.</span>
<span id="cb82-106"><a href="#cb82-106"></a></span>
<span id="cb82-107"><a href="#cb82-107"></a>\</span>
<span id="cb82-108"><a href="#cb82-108"></a>\</span>
<span id="cb82-109"><a href="#cb82-109"></a>\</span>
<span id="cb82-110"><a href="#cb82-110"></a>\</span>
<span id="cb82-111"><a href="#cb82-111"></a></span>
<span id="cb82-112"><a href="#cb82-112"></a>**EXAMPLE 4: reshape it with your mind**</span>
<span id="cb82-113"><a href="#cb82-113"></a></span>
<span id="cb82-114"><a href="#cb82-114"></a>Let's calculate the *difference* in average body mass, male vs female, for each species. Since `penguin_avg` is small, we *could* do these calculations by hand. But this doesn't scale up to bigger datasets.</span>
<span id="cb82-115"><a href="#cb82-115"></a></span>
<span id="cb82-116"><a href="#cb82-116"></a><span class="ss">-   </span>Sketch out (on paper, in your head, anything) how this data would need to be *reshaped*, *without* losing any information, in order to calculate the differences in average body mass using our wrangling verbs. Make it as specific as possible, with column labels, entries, correct numbers, etc.</span>
<span id="cb82-117"><a href="#cb82-117"></a></span>
<span id="cb82-118"><a href="#cb82-118"></a><span class="ss">-   </span>Identify the units of observation.</span>
<span id="cb82-119"><a href="#cb82-119"></a></span>
<span id="cb82-122"><a href="#cb82-122"></a><span class="in">```{r}</span></span>
<span id="cb82-123"><a href="#cb82-123"></a>penguin_avg</span>
<span id="cb82-124"><a href="#cb82-124"></a><span class="in">```</span></span>
<span id="cb82-125"><a href="#cb82-125"></a></span>
<span id="cb82-126"><a href="#cb82-126"></a>\</span>
<span id="cb82-127"><a href="#cb82-127"></a>\</span>
<span id="cb82-128"><a href="#cb82-128"></a>\</span>
<span id="cb82-129"><a href="#cb82-129"></a>\</span>
<span id="cb82-130"><a href="#cb82-130"></a>\</span>
<span id="cb82-131"><a href="#cb82-131"></a></span>
<span id="cb82-132"><a href="#cb82-132"></a>**Wider vs Longer formats**</span>
<span id="cb82-133"><a href="#cb82-133"></a></span>
<span id="cb82-134"><a href="#cb82-134"></a>Making our data *longer* or *wider* reshapes the data, changing the units of observation while retaining *all* raw information:</span>
<span id="cb82-135"><a href="#cb82-135"></a></span>
<span id="cb82-136"><a href="#cb82-136"></a><span class="ss">1.  </span>Make the data *longer*, i.e. combine values from multiple variables into 1 variable. EXAMPLE: `1999` and `2000` represent two years. We want to *combine* their results into 1 variable without losing any information.</span>
<span id="cb82-137"><a href="#cb82-137"></a></span>
<span id="cb82-138"><a href="#cb82-138"></a><span class="al">![](https://mac-stat.github.io/images/112/pivot_longer.png)</span></span>
<span id="cb82-139"><a href="#cb82-139"></a></span>
<span id="cb82-140"><a href="#cb82-140"></a><span class="ss">2.  </span>Make the data *wider*, i.e. spread out the values across new variables. EXAMPLE: `cases` and `pop` represent two categories within `type`. To compare or combine their `count` outcomes side-by-side, we can *separate* them into their own variables.</span>
<span id="cb82-141"><a href="#cb82-141"></a></span>
<span id="cb82-142"><a href="#cb82-142"></a><span class="al">![](https://mac-stat.github.io/images/112/pivot_wider.png)</span></span>
<span id="cb82-143"><a href="#cb82-143"></a></span>
<span id="cb82-144"><a href="#cb82-144"></a>\</span>
<span id="cb82-145"><a href="#cb82-145"></a>\</span>
<span id="cb82-146"><a href="#cb82-146"></a>\</span>
<span id="cb82-147"><a href="#cb82-147"></a>\</span>
<span id="cb82-148"><a href="#cb82-148"></a></span>
<span id="cb82-149"><a href="#cb82-149"></a>**EXAMPLE 5: pivot wider**</span>
<span id="cb82-150"><a href="#cb82-150"></a></span>
<span id="cb82-151"><a href="#cb82-151"></a>Because it's a small enough dataset to examine all at once, let's start with our <span class="in">`penguin_avg`</span> data:</span>
<span id="cb82-152"><a href="#cb82-152"></a></span>
<span id="cb82-155"><a href="#cb82-155"></a><span class="in">```{r}</span></span>
<span id="cb82-156"><a href="#cb82-156"></a>penguin_avg</span>
<span id="cb82-157"><a href="#cb82-157"></a><span class="in">```</span></span>
<span id="cb82-158"><a href="#cb82-158"></a></span>
<span id="cb82-159"><a href="#cb82-159"></a>With the goal of being able to calculate the *difference* in average body mass, male vs female, for each species, let's make the dataset *wider*. That is, let's get one row per <span class="in">`species`</span> with separate columns for the average body mass by <span class="in">`sex`</span>. Put this code into a chunk and run it:</span>
<span id="cb82-160"><a href="#cb82-160"></a></span>
<span id="cb82-161"><a href="#cb82-161"></a>penguin_avg |<span class="sc">\&gt;</span> pivot_wider(names_from = sex, values_from = avg_body_mass)</span>
<span id="cb82-162"><a href="#cb82-162"></a></span>
<span id="cb82-165"><a href="#cb82-165"></a><span class="in">```{r}</span></span>
<span id="cb82-166"><a href="#cb82-166"></a>penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb82-167"><a href="#cb82-167"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass)</span>
<span id="cb82-168"><a href="#cb82-168"></a><span class="in">```</span></span>
<span id="cb82-169"><a href="#cb82-169"></a></span>
<span id="cb82-170"><a href="#cb82-170"></a>::: {.callout-note title="Pivot Wider"}</span>
<span id="cb82-171"><a href="#cb82-171"></a></span>
<span id="cb82-172"><a href="#cb82-172"></a><span class="ss">-   </span><span class="in">`names_from`</span> = the variable whose values we want to separate into their own columns, i.e. where we want to get the new column *names from*</span>
<span id="cb82-173"><a href="#cb82-173"></a><span class="ss">-   </span><span class="in">`values_from`</span> = which variable to take the new column *values from*</span>
<span id="cb82-174"><a href="#cb82-174"></a></span>
<span id="cb82-175"><a href="#cb82-175"></a>:::</span>
<span id="cb82-176"><a href="#cb82-176"></a></span>
<span id="cb82-177"><a href="#cb82-177"></a>FOLLOW-UP:</span>
<span id="cb82-178"><a href="#cb82-178"></a></span>
<span id="cb82-179"><a href="#cb82-179"></a><span class="ss">-   </span>What are the units of observation?</span>
<span id="cb82-180"><a href="#cb82-180"></a>adelie, gentoo, chinstrap</span>
<span id="cb82-181"><a href="#cb82-181"></a></span>
<span id="cb82-182"><a href="#cb82-182"></a><span class="ss">-   </span>Did we lose any information when we widened the data?</span>
<span id="cb82-183"><a href="#cb82-183"></a>no</span>
<span id="cb82-184"><a href="#cb82-184"></a></span>
<span id="cb82-185"><a href="#cb82-185"></a><span class="ss">-   </span>Use the wide data to calculate the difference in average body mass, male vs female, for each species.</span>
<span id="cb82-186"><a href="#cb82-186"></a></span>
<span id="cb82-189"><a href="#cb82-189"></a><span class="in">```{r}</span></span>
<span id="cb82-190"><a href="#cb82-190"></a>penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb82-191"><a href="#cb82-191"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass) <span class="sc">|&gt;</span> </span>
<span id="cb82-192"><a href="#cb82-192"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> male <span class="sc">-</span> female)</span>
<span id="cb82-193"><a href="#cb82-193"></a><span class="in">```</span></span>
<span id="cb82-194"><a href="#cb82-194"></a></span>
<span id="cb82-195"><a href="#cb82-195"></a>\</span>
<span id="cb82-196"><a href="#cb82-196"></a>\</span>
<span id="cb82-197"><a href="#cb82-197"></a>\</span>
<span id="cb82-198"><a href="#cb82-198"></a>\</span>
<span id="cb82-199"><a href="#cb82-199"></a></span>
<span id="cb82-200"><a href="#cb82-200"></a>**EXAMPLE 6: Pivot longer**</span>
<span id="cb82-201"><a href="#cb82-201"></a></span>
<span id="cb82-202"><a href="#cb82-202"></a>Let's store our wide data:</span>
<span id="cb82-203"><a href="#cb82-203"></a></span>
<span id="cb82-206"><a href="#cb82-206"></a><span class="in">```{r}</span></span>
<span id="cb82-207"><a href="#cb82-207"></a>penguin_avg_wide <span class="ot">&lt;-</span> penguin_avg <span class="sc">|&gt;</span> </span>
<span id="cb82-208"><a href="#cb82-208"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> avg_body_mass)</span>
<span id="cb82-209"><a href="#cb82-209"></a></span>
<span id="cb82-210"><a href="#cb82-210"></a>penguin_avg_wide</span>
<span id="cb82-211"><a href="#cb82-211"></a><span class="in">```</span></span>
<span id="cb82-212"><a href="#cb82-212"></a></span>
<span id="cb82-213"><a href="#cb82-213"></a>Suppose we wanted to change this data back to a *longer* format. In general, this happens when some variables (here `female` and `male`) represent two categories or values of some *broader* variable (here <span class="in">`sex`</span>), and we want to combine them into that 1 variable without losing any information. Let's <span class="in">`pivot_longer()`</span>:</span>
<span id="cb82-214"><a href="#cb82-214"></a></span>
<span id="cb82-217"><a href="#cb82-217"></a><span class="in">```{r}</span></span>
<span id="cb82-218"><a href="#cb82-218"></a><span class="co"># We can either communicate which variables we WANT to collect into a single column (female, male)</span></span>
<span id="cb82-219"><a href="#cb82-219"></a>penguin_avg_wide <span class="sc">|&gt;</span> </span>
<span id="cb82-220"><a href="#cb82-220"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(female, male), <span class="at">names_to =</span> <span class="st">"sex"</span>, <span class="at">values_to =</span> <span class="st">"avg_body_mass"</span>)</span>
<span id="cb82-221"><a href="#cb82-221"></a></span>
<span id="cb82-222"><a href="#cb82-222"></a><span class="co"># Or which variable(s) we do NOT want to collect into a single column (sex)</span></span>
<span id="cb82-223"><a href="#cb82-223"></a>penguin_avg_wide <span class="sc">|&gt;</span> </span>
<span id="cb82-224"><a href="#cb82-224"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>species, <span class="at">names_to =</span> <span class="st">"sex"</span>, <span class="at">values_to =</span> <span class="st">"avg_body_mass"</span>)</span>
<span id="cb82-225"><a href="#cb82-225"></a><span class="in">```</span></span>
<span id="cb82-226"><a href="#cb82-226"></a></span>
<span id="cb82-227"><a href="#cb82-227"></a>::: {.callout-note title="Pivot Longer"}</span>
<span id="cb82-228"><a href="#cb82-228"></a></span>
<span id="cb82-229"><a href="#cb82-229"></a><span class="ss">-   </span><span class="in">`cols`</span> = the columns (variables) to collect into a single, new variable. we can also specify what variables we *don't* want to collect</span>
<span id="cb82-230"><a href="#cb82-230"></a><span class="ss">-   </span><span class="in">`names_to`</span> = the name of the new variable which will include the *names* or labels of the collected variables</span>
<span id="cb82-231"><a href="#cb82-231"></a><span class="ss">-   </span><span class="in">`values_to`</span> = the name of the new variable which will include the *values* of the collected variables</span>
<span id="cb82-232"><a href="#cb82-232"></a></span>
<span id="cb82-233"><a href="#cb82-233"></a>:::</span>
<span id="cb82-234"><a href="#cb82-234"></a></span>
<span id="cb82-235"><a href="#cb82-235"></a>FOLLOW-UP:</span>
<span id="cb82-236"><a href="#cb82-236"></a></span>
<span id="cb82-237"><a href="#cb82-237"></a><span class="ss">-   </span>What are the units of observation?</span>
<span id="cb82-238"><a href="#cb82-238"></a>species and sex </span>
<span id="cb82-239"><a href="#cb82-239"></a></span>
<span id="cb82-240"><a href="#cb82-240"></a><span class="ss">-   </span>Did we lose any information when we lengthened the data?</span>
<span id="cb82-241"><a href="#cb82-241"></a>no</span>
<span id="cb82-242"><a href="#cb82-242"></a></span>
<span id="cb82-243"><a href="#cb82-243"></a><span class="ss">-   </span>Why did we put the variables in quotes "" here but not when we used <span class="in">`pivot_wider()`</span>?</span>
<span id="cb82-244"><a href="#cb82-244"></a>beacuse we are using the name of the column</span>
<span id="cb82-245"><a href="#cb82-245"></a></span>
<span id="cb82-246"><a href="#cb82-246"></a>\</span>
<span id="cb82-247"><a href="#cb82-247"></a>\</span>
<span id="cb82-248"><a href="#cb82-248"></a>\</span>
<span id="cb82-249"><a href="#cb82-249"></a>\</span>
<span id="cb82-250"><a href="#cb82-250"></a></span>
<span id="cb82-251"><a href="#cb82-251"></a>**EXAMPLE 7: Practice**</span>
<span id="cb82-252"><a href="#cb82-252"></a></span>
<span id="cb82-253"><a href="#cb82-253"></a>Let's make up some data on the orders of 2 different customers at 3 different restaurants:</span>
<span id="cb82-254"><a href="#cb82-254"></a></span>
<span id="cb82-257"><a href="#cb82-257"></a><span class="in">```{r}</span></span>
<span id="cb82-258"><a href="#cb82-258"></a>food <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb82-259"><a href="#cb82-259"></a>  <span class="at">customer =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb82-260"><a href="#cb82-260"></a>  <span class="at">restaurant =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Shish"</span>, <span class="st">"FrenchMeadow"</span>, <span class="st">"DunnBros"</span>), <span class="dv">2</span>),</span>
<span id="cb82-261"><a href="#cb82-261"></a>  <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"falafel"</span>, <span class="st">"salad"</span>, <span class="st">"coffee"</span>, <span class="st">"baklava"</span>, <span class="st">"pastry"</span>, <span class="st">"tea"</span>)</span>
<span id="cb82-262"><a href="#cb82-262"></a>)</span>
<span id="cb82-263"><a href="#cb82-263"></a>food</span>
<span id="cb82-264"><a href="#cb82-264"></a><span class="in">```</span></span>
<span id="cb82-265"><a href="#cb82-265"></a></span>
<span id="cb82-266"><a href="#cb82-266"></a>The units of observation in <span class="in">`food`</span> are customer / restaurant combinations. Wrangle this data so that the units of observation are customers, spreading the restaurants into separate columns.</span>
<span id="cb82-267"><a href="#cb82-267"></a></span>
<span id="cb82-270"><a href="#cb82-270"></a><span class="in">```{r}</span></span>
<span id="cb82-271"><a href="#cb82-271"></a>food <span class="sc">|&gt;</span> </span>
<span id="cb82-272"><a href="#cb82-272"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> restaurant, <span class="at">values_from =</span> order)</span>
<span id="cb82-273"><a href="#cb82-273"></a><span class="in">```</span></span>
<span id="cb82-274"><a href="#cb82-274"></a></span>
<span id="cb82-275"><a href="#cb82-275"></a>Consider 2 more customers:</span>
<span id="cb82-276"><a href="#cb82-276"></a></span>
<span id="cb82-279"><a href="#cb82-279"></a><span class="in">```{r}</span></span>
<span id="cb82-280"><a href="#cb82-280"></a>more_food <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb82-281"><a href="#cb82-281"></a>  <span class="at">customer =</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"D"</span>),</span>
<span id="cb82-282"><a href="#cb82-282"></a>  <span class="at">Shish =</span> <span class="fu">c</span>(<span class="st">"coffee"</span>, <span class="st">"maza"</span>),</span>
<span id="cb82-283"><a href="#cb82-283"></a>  <span class="at">FrenchMeadow =</span> <span class="fu">c</span>(<span class="st">"soup"</span>, <span class="st">"sandwich"</span>),</span>
<span id="cb82-284"><a href="#cb82-284"></a>  <span class="at">DunnBros =</span> <span class="fu">c</span>(<span class="st">"cookie"</span>, <span class="st">"coffee"</span>)</span>
<span id="cb82-285"><a href="#cb82-285"></a>)</span>
<span id="cb82-286"><a href="#cb82-286"></a>more_food</span>
<span id="cb82-287"><a href="#cb82-287"></a><span class="in">```</span></span>
<span id="cb82-288"><a href="#cb82-288"></a></span>
<span id="cb82-289"><a href="#cb82-289"></a>Wrangle this data so that the 3 restaurant columns are combined into 1, hence the units of observation are customer / restaurant combinations.</span>
<span id="cb82-290"><a href="#cb82-290"></a></span>
<span id="cb82-293"><a href="#cb82-293"></a><span class="in">```{r}</span></span>
<span id="cb82-294"><a href="#cb82-294"></a>more_food <span class="sc">|&gt;</span> </span>
<span id="cb82-295"><a href="#cb82-295"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>customer, <span class="at">names_to =</span> <span class="st">"restaurant"</span>, <span class="at">values_to =</span> <span class="st">"order"</span>)</span>
<span id="cb82-296"><a href="#cb82-296"></a><span class="in">```</span></span>
<span id="cb82-297"><a href="#cb82-297"></a></span>
<span id="cb82-298"><a href="#cb82-298"></a>\</span>
<span id="cb82-299"><a href="#cb82-299"></a>\</span>
<span id="cb82-300"><a href="#cb82-300"></a>\</span>
<span id="cb82-301"><a href="#cb82-301"></a>\</span>
<span id="cb82-302"><a href="#cb82-302"></a></span>
<span id="cb82-303"><a href="#cb82-303"></a><span class="fu">## Exercises</span></span>
<span id="cb82-304"><a href="#cb82-304"></a></span>
<span id="cb82-305"><a href="#cb82-305"></a><span class="fu">### Exercise 1: What's the problem? {.unnumbered}</span></span>
<span id="cb82-306"><a href="#cb82-306"></a></span>
<span id="cb82-307"><a href="#cb82-307"></a>Consider data on a sleep study in which subjects received only 3 hours of sleep per night.  Each day, their reaction time to a stimulus (in ms) was recorded.<span class="ot">[^10-reshaping-data-1]</span></span>
<span id="cb82-308"><a href="#cb82-308"></a></span>
<span id="cb82-309"><a href="#cb82-309"></a><span class="ot">[^10-reshaping-data-1]: </span>Gregory Belenky, Nancy J. Wesensten, David R. Thorne, Maria L. Thomas, Helen C. Sing, Daniel P. Redmond, Michael B. Russo and Thomas J. Balkin (2003) Patterns of performance degradation and restoration during sleep restriction and subsequent recovery: a sleep dose-response study. Journal of Sleep Research 12, 1–12.</span>
<span id="cb82-310"><a href="#cb82-310"></a></span>
<span id="cb82-313"><a href="#cb82-313"></a><span class="in">```{r}</span></span>
<span id="cb82-314"><a href="#cb82-314"></a>sleep_wide <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://mac-stat.github.io/data/sleep_wide.csv"</span>)</span>
<span id="cb82-315"><a href="#cb82-315"></a></span>
<span id="cb82-316"><a href="#cb82-316"></a><span class="fu">head</span>(sleep_wide)</span>
<span id="cb82-317"><a href="#cb82-317"></a><span class="in">```</span></span>
<span id="cb82-318"><a href="#cb82-318"></a></span>
<span id="cb82-319"><a href="#cb82-319"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-320"><a href="#cb82-320"></a></span>
<span id="cb82-321"><a href="#cb82-321"></a>What are the units of observation in <span class="in">`sleep_wide`</span>?</span>
<span id="cb82-322"><a href="#cb82-322"></a><span class="ss">  - </span>subjects</span>
<span id="cb82-323"><a href="#cb82-323"></a></span>
<span id="cb82-324"><a href="#cb82-324"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-325"><a href="#cb82-325"></a></span>
<span id="cb82-326"><a href="#cb82-326"></a>Suppose I ask you to plot each subject's reaction time (y-axis) vs the number of days of sleep restriction (x-axis). "Sketch" out in words what the first few rows of the data need to look like in order to do this. It might help to think about what you'd need to complete the plotting frame:</span>
<span id="cb82-327"><a href="#cb82-327"></a></span>
<span id="cb82-328"><a href="#cb82-328"></a><span class="in">`ggplot(___, aes(y = ___, x = ___, color = ___))`</span></span>
<span id="cb82-329"><a href="#cb82-329"></a></span>
<span id="cb82-330"><a href="#cb82-330"></a><span class="ss">- </span>we would need the days to be the units of observations, so it owuld look like |day_ | subject | performance |</span>
<span id="cb82-331"><a href="#cb82-331"></a> 1    | 308     | 249.56</span>
<span id="cb82-332"><a href="#cb82-332"></a> </span>
<span id="cb82-333"><a href="#cb82-333"></a></span>
<span id="cb82-334"><a href="#cb82-334"></a><span class="fu">#### Part c {.unnumbered}</span></span>
<span id="cb82-335"><a href="#cb82-335"></a></span>
<span id="cb82-336"><a href="#cb82-336"></a>How can you obtain the dataset you sketched in part b? You would want to use pivot_longer</span>
<span id="cb82-337"><a href="#cb82-337"></a></span>
<span id="cb82-338"><a href="#cb82-338"></a><span class="ss">-   </span>just using <span class="in">`sleep_wide`</span></span>
<span id="cb82-339"><a href="#cb82-339"></a><span class="ss">-   </span><span class="in">`pivot_longer()`</span></span>
<span id="cb82-340"><a href="#cb82-340"></a><span class="ss">-   </span><span class="in">`pivot_wider()`</span></span>
<span id="cb82-341"><a href="#cb82-341"></a></span>
<span id="cb82-342"><a href="#cb82-342"></a>\</span>
<span id="cb82-343"><a href="#cb82-343"></a>\</span>
<span id="cb82-344"><a href="#cb82-344"></a>\</span>
<span id="cb82-345"><a href="#cb82-345"></a>\</span>
<span id="cb82-346"><a href="#cb82-346"></a></span>
<span id="cb82-347"><a href="#cb82-347"></a><span class="fu">### Exercise 2: Pivot longer {.unnumbered}</span></span>
<span id="cb82-348"><a href="#cb82-348"></a></span>
<span id="cb82-349"><a href="#cb82-349"></a>To plot reaction time by day for each subject, we need to reshape the data into a **long** format where each row represents a subject/day combination. Specifically, we want a dataset with 3 columns and a first few rows that look something like this:</span>
<span id="cb82-350"><a href="#cb82-350"></a></span>
<span id="cb82-351"><a href="#cb82-351"></a>| Subject | day | reaction_time |</span>
<span id="cb82-352"><a href="#cb82-352"></a>|--------:|----:|--------------:|</span>
<span id="cb82-353"><a href="#cb82-353"></a>|     308 |   0 |        249.56 |</span>
<span id="cb82-354"><a href="#cb82-354"></a>|     308 |   1 |        258.70 |</span>
<span id="cb82-355"><a href="#cb82-355"></a>|     308 |   2 |        250.80 |</span>
<span id="cb82-356"><a href="#cb82-356"></a></span>
<span id="cb82-357"><a href="#cb82-357"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-358"><a href="#cb82-358"></a></span>
<span id="cb82-359"><a href="#cb82-359"></a>Use <span class="in">`pivot_longer()`</span> to create the long-format dataset above. Show the first 3 lines (<span class="in">`head(3)`</span>), which should be *similar* to those above. Follow-up: Thinking forward to plotting reaction time vs day for each subject, what would you like to fix / change about this dataset?</span>
<span id="cb82-360"><a href="#cb82-360"></a></span>
<span id="cb82-363"><a href="#cb82-363"></a><span class="in">```{r}</span></span>
<span id="cb82-364"><a href="#cb82-364"></a><span class="co"># For cols, try 2 appproaches: using - and starts_with</span></span>
<span id="cb82-365"><a href="#cb82-365"></a> sleep_wide <span class="sc">|&gt;</span> </span>
<span id="cb82-366"><a href="#cb82-366"></a>   <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject, <span class="at">names_to =</span> <span class="st">"day"</span>, <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span>
<span id="cb82-367"><a href="#cb82-367"></a>sleep_wide <span class="sc">|&gt;</span> <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"day"</span>), <span class="at">names_to =</span> <span class="st">"day"</span>, <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span>
<span id="cb82-368"><a href="#cb82-368"></a><span class="in">```</span></span>
<span id="cb82-369"><a href="#cb82-369"></a></span>
<span id="cb82-370"><a href="#cb82-370"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-371"><a href="#cb82-371"></a></span>
<span id="cb82-372"><a href="#cb82-372"></a>Run this chunk:</span>
<span id="cb82-373"><a href="#cb82-373"></a></span>
<span id="cb82-376"><a href="#cb82-376"></a><span class="in">```{r}</span></span>
<span id="cb82-377"><a href="#cb82-377"></a>sleep_long <span class="ot">&lt;-</span> sleep_wide <span class="sc">|&gt;</span></span>
<span id="cb82-378"><a href="#cb82-378"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject,</span>
<span id="cb82-379"><a href="#cb82-379"></a>               <span class="at">names_to =</span> <span class="st">"day"</span>,</span>
<span id="cb82-380"><a href="#cb82-380"></a>               <span class="at">names_prefix =</span> <span class="st">"day_"</span>,</span>
<span id="cb82-381"><a href="#cb82-381"></a>               <span class="at">values_to =</span> <span class="st">"reaction_time"</span>)</span>
<span id="cb82-382"><a href="#cb82-382"></a></span>
<span id="cb82-383"><a href="#cb82-383"></a><span class="fu">head</span>(sleep_long)</span>
<span id="cb82-384"><a href="#cb82-384"></a><span class="in">```</span></span>
<span id="cb82-385"><a href="#cb82-385"></a></span>
<span id="cb82-386"><a href="#cb82-386"></a>Follow-up:</span>
<span id="cb82-387"><a href="#cb82-387"></a></span>
<span id="cb82-388"><a href="#cb82-388"></a><span class="ss">-   </span>Besides putting each argument on a different line for readability and storing the results, what changed in the code?</span>
<span id="cb82-389"><a href="#cb82-389"></a>    day_ was removed from the day column</span>
<span id="cb82-390"><a href="#cb82-390"></a><span class="ss">-   </span>How did this impact how the values are recorded in the <span class="in">`day`</span> column?</span>
<span id="cb82-391"><a href="#cb82-391"></a><span class="ss">    - </span>it got rid of the day_ prefix in the vaules of the column</span>
<span id="cb82-392"><a href="#cb82-392"></a></span>
<span id="cb82-393"><a href="#cb82-393"></a><span class="fu">#### Part c {.unnumbered}</span></span>
<span id="cb82-394"><a href="#cb82-394"></a></span>
<span id="cb82-395"><a href="#cb82-395"></a>Using <span class="in">`sleep_long`</span>, construct a line plot of reaction time vs day for each subject. This will look goofy no matter what you do. Why? HINT: look back at <span class="in">`head(sleep_long)`</span>. What class or type of variables are <span class="in">`Subject`</span> and <span class="in">`day`</span>? What do we *want* them to be? (<span class="in">`Subject`</span> is integer and <span class="in">`day`</span> is character but we want <span class="in">`subject`</span> as a factor and <span class="in">`day`</span> as a numeric value )</span>
<span id="cb82-396"><a href="#cb82-396"></a></span>
<span id="cb82-399"><a href="#cb82-399"></a><span class="in">```{r}</span></span>
<span id="cb82-400"><a href="#cb82-400"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<span id="cb82-401"><a href="#cb82-401"></a>  <span class="fu">geom_line</span>()</span>
<span id="cb82-402"><a href="#cb82-402"></a><span class="in">```</span></span>
<span id="cb82-403"><a href="#cb82-403"></a></span>
<span id="cb82-404"><a href="#cb82-404"></a>\</span>
<span id="cb82-405"><a href="#cb82-405"></a>\</span>
<span id="cb82-406"><a href="#cb82-406"></a>\</span>
<span id="cb82-407"><a href="#cb82-407"></a>\</span>
<span id="cb82-408"><a href="#cb82-408"></a></span>
<span id="cb82-409"><a href="#cb82-409"></a><span class="fu">### Exercise 3: Changing variable classes &amp; plotting {.unnumbered}</span></span>
<span id="cb82-410"><a href="#cb82-410"></a></span>
<span id="cb82-411"><a href="#cb82-411"></a>Let's finalize <span class="in">`sleep_long`</span> by *mutating* the <span class="in">`Subject`</span> variable to be a <span class="in">`factor`</span> (categorical) and the <span class="in">`day`</span> variable to be <span class="in">`numeric`</span> (quantitative). Take note of the <span class="in">`mutate()`</span> code! You'll use this type of code a lot.</span>
<span id="cb82-412"><a href="#cb82-412"></a></span>
<span id="cb82-415"><a href="#cb82-415"></a><span class="in">```{r}</span></span>
<span id="cb82-416"><a href="#cb82-416"></a>sleep_long <span class="ot">&lt;-</span> sleep_wide <span class="sc">|&gt;</span></span>
<span id="cb82-417"><a href="#cb82-417"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Subject,</span>
<span id="cb82-418"><a href="#cb82-418"></a>               <span class="at">names_to =</span> <span class="st">"day"</span>,</span>
<span id="cb82-419"><a href="#cb82-419"></a>               <span class="at">names_prefix =</span> <span class="st">"day_"</span>,</span>
<span id="cb82-420"><a href="#cb82-420"></a>               <span class="at">values_to =</span> <span class="st">"reaction_time"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb82-421"><a href="#cb82-421"></a>  <span class="fu">mutate</span>(<span class="at">Subject =</span> <span class="fu">as.factor</span>(Subject), <span class="at">day =</span> <span class="fu">as.numeric</span>(day))</span>
<span id="cb82-422"><a href="#cb82-422"></a></span>
<span id="cb82-423"><a href="#cb82-423"></a><span class="co"># Check it out</span></span>
<span id="cb82-424"><a href="#cb82-424"></a><span class="co"># Same data, different class</span></span>
<span id="cb82-425"><a href="#cb82-425"></a><span class="fu">head</span>(sleep_long)</span>
<span id="cb82-426"><a href="#cb82-426"></a><span class="in">```</span></span>
<span id="cb82-427"><a href="#cb82-427"></a></span>
<span id="cb82-428"><a href="#cb82-428"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-429"><a href="#cb82-429"></a></span>
<span id="cb82-430"><a href="#cb82-430"></a>*Now* make some plots.</span>
<span id="cb82-431"><a href="#cb82-431"></a></span>
<span id="cb82-434"><a href="#cb82-434"></a><span class="in">```{r}</span></span>
<span id="cb82-435"><a href="#cb82-435"></a><span class="co"># Make a line plot of reaction time by day for each subject</span></span>
<span id="cb82-436"><a href="#cb82-436"></a><span class="co"># Put these all on the same frame</span></span>
<span id="cb82-437"><a href="#cb82-437"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time, <span class="at">color =</span> Subject)) <span class="sc">+</span></span>
<span id="cb82-438"><a href="#cb82-438"></a>  <span class="fu">geom_line</span>()</span>
<span id="cb82-439"><a href="#cb82-439"></a><span class="in">```</span></span>
<span id="cb82-440"><a href="#cb82-440"></a></span>
<span id="cb82-443"><a href="#cb82-443"></a><span class="in">```{r}</span></span>
<span id="cb82-444"><a href="#cb82-444"></a><span class="co"># Make a line plot of reaction time by day for each subject</span></span>
<span id="cb82-445"><a href="#cb82-445"></a><span class="co"># Put these all on separate frames (one per subject)</span></span>
<span id="cb82-446"><a href="#cb82-446"></a><span class="fu">ggplot</span>(sleep_long, <span class="fu">aes</span>(<span class="at">x =</span> day, <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<span id="cb82-447"><a href="#cb82-447"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb82-448"><a href="#cb82-448"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Subject)</span>
<span id="cb82-449"><a href="#cb82-449"></a><span class="in">```</span></span>
<span id="cb82-450"><a href="#cb82-450"></a></span>
<span id="cb82-451"><a href="#cb82-451"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-452"><a href="#cb82-452"></a></span>
<span id="cb82-453"><a href="#cb82-453"></a>Summarize what you learned from the plots. For example:</span>
<span id="cb82-454"><a href="#cb82-454"></a></span>
<span id="cb82-455"><a href="#cb82-455"></a><span class="ss">-   </span>What's the general relationship between reaction time and sleep?</span>
<span id="cb82-456"><a href="#cb82-456"></a>generally the later the day in the study related to slower reaction times</span>
<span id="cb82-457"><a href="#cb82-457"></a><span class="ss">-   </span>Is this the same for everybody? What differs?</span>
<span id="cb82-458"><a href="#cb82-458"></a>No this was not the same for some people it got faster at some points but then when down again and for others it contiunally got slower.</span>
<span id="cb82-459"><a href="#cb82-459"></a></span>
<span id="cb82-460"><a href="#cb82-460"></a>\</span>
<span id="cb82-461"><a href="#cb82-461"></a>\</span>
<span id="cb82-462"><a href="#cb82-462"></a>\</span>
<span id="cb82-463"><a href="#cb82-463"></a>\</span>
<span id="cb82-464"><a href="#cb82-464"></a></span>
<span id="cb82-465"><a href="#cb82-465"></a><span class="fu">### Exercise 4: Pivot wider {.unnumbered}</span></span>
<span id="cb82-466"><a href="#cb82-466"></a></span>
<span id="cb82-467"><a href="#cb82-467"></a>Make the data *wide* again, with each day becoming its own column.</span>
<span id="cb82-468"><a href="#cb82-468"></a></span>
<span id="cb82-469"><a href="#cb82-469"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-470"><a href="#cb82-470"></a></span>
<span id="cb82-471"><a href="#cb82-471"></a>Adjust the code below. What don't you like about the column labels?</span>
<span id="cb82-472"><a href="#cb82-472"></a></span>
<span id="cb82-475"><a href="#cb82-475"></a><span class="in">```{r}</span></span>
<span id="cb82-476"><a href="#cb82-476"></a> sleep_long <span class="sc">|&gt;</span></span>
<span id="cb82-477"><a href="#cb82-477"></a>   <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> day, <span class="at">values_from =</span> reaction_time) <span class="sc">|&gt;</span> </span>
<span id="cb82-478"><a href="#cb82-478"></a>   <span class="fu">head</span>()</span>
<span id="cb82-479"><a href="#cb82-479"></a><span class="in">```</span></span>
<span id="cb82-480"><a href="#cb82-480"></a></span>
<span id="cb82-481"><a href="#cb82-481"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-482"><a href="#cb82-482"></a></span>
<span id="cb82-483"><a href="#cb82-483"></a>Using your intuition, adjust your code from part a to name the reaction time columns "day_0", "day_1", etc.</span>
<span id="cb82-484"><a href="#cb82-484"></a></span>
<span id="cb82-487"><a href="#cb82-487"></a><span class="in">```{r}</span></span>
<span id="cb82-488"><a href="#cb82-488"></a> sleep_long <span class="sc">|&gt;</span></span>
<span id="cb82-489"><a href="#cb82-489"></a>   <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> day, <span class="at">values_from =</span> reaction_time, <span class="at">names_prefix =</span> <span class="st">"day_"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb82-490"><a href="#cb82-490"></a>   <span class="fu">head</span>()</span>
<span id="cb82-491"><a href="#cb82-491"></a><span class="in">```</span></span>
<span id="cb82-492"><a href="#cb82-492"></a></span>
<span id="cb82-493"><a href="#cb82-493"></a>\</span>
<span id="cb82-494"><a href="#cb82-494"></a>\</span>
<span id="cb82-495"><a href="#cb82-495"></a>\</span>
<span id="cb82-496"><a href="#cb82-496"></a>\</span>
<span id="cb82-497"><a href="#cb82-497"></a></span>
<span id="cb82-498"><a href="#cb82-498"></a><span class="fu">### Exercise 5: Practice with Billboard charts {.unnumbered}</span></span>
<span id="cb82-499"><a href="#cb82-499"></a></span>
<span id="cb82-500"><a href="#cb82-500"></a>Load data on songs that hit the <span class="in">`billboard`</span> charts around the year 2000. Included for each song is the <span class="in">`artist`</span> name, <span class="in">`track`</span> name, the date it hit the charts (<span class="in">`date.enter`</span>), and <span class="in">`wk`</span>-related variables that indicate rankings in each subsequent week on the charts:</span>
<span id="cb82-501"><a href="#cb82-501"></a></span>
<span id="cb82-504"><a href="#cb82-504"></a><span class="in">```{r}</span></span>
<span id="cb82-505"><a href="#cb82-505"></a><span class="co"># Load data</span></span>
<span id="cb82-506"><a href="#cb82-506"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb82-507"><a href="#cb82-507"></a><span class="fu">data</span>(<span class="st">"billboard"</span>)</span>
<span id="cb82-508"><a href="#cb82-508"></a></span>
<span id="cb82-509"><a href="#cb82-509"></a><span class="co"># Check it out</span></span>
<span id="cb82-510"><a href="#cb82-510"></a><span class="fu">head</span>(billboard)</span>
<span id="cb82-511"><a href="#cb82-511"></a><span class="in">```</span></span>
<span id="cb82-512"><a href="#cb82-512"></a></span>
<span id="cb82-513"><a href="#cb82-513"></a>In using this data, you'll need to determine if and when the data needs to be reshaped for the task at hand.</span>
<span id="cb82-514"><a href="#cb82-514"></a></span>
<span id="cb82-515"><a href="#cb82-515"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-516"><a href="#cb82-516"></a></span>
<span id="cb82-517"><a href="#cb82-517"></a>Construct and summarize a plot of how a song's Billboard ranking its 2nd week on the chart (y-axis) is related to its ranking the 1st week on the charts (x-axis). Add a reference line <span class="in">`geom_abline(intercept = 0, slope = 1)`</span>. Songs *above* this line *improved* their rankings from the 1st to 2nd week.</span>
<span id="cb82-518"><a href="#cb82-518"></a></span>
<span id="cb82-521"><a href="#cb82-521"></a><span class="in">```{r}</span></span>
<span id="cb82-522"><a href="#cb82-522"></a><span class="fu">ggplot</span>(billboard, <span class="fu">aes</span>(<span class="at">x =</span> wk1, <span class="at">y =</span> wk2)) <span class="sc">+</span> </span>
<span id="cb82-523"><a href="#cb82-523"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-524"><a href="#cb82-524"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>)</span>
<span id="cb82-525"><a href="#cb82-525"></a><span class="in">```</span></span>
<span id="cb82-526"><a href="#cb82-526"></a></span>
<span id="cb82-527"><a href="#cb82-527"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-528"><a href="#cb82-528"></a></span>
<span id="cb82-529"><a href="#cb82-529"></a>Use your wrangling tools to identify *which* songs are those above the line in Part a, i.e. with rankgings that went up from week 1 to week 2.</span>
<span id="cb82-530"><a href="#cb82-530"></a></span>
<span id="cb82-533"><a href="#cb82-533"></a><span class="in">```{r}</span></span>
<span id="cb82-534"><a href="#cb82-534"></a>billboard <span class="sc">|&gt;</span></span>
<span id="cb82-535"><a href="#cb82-535"></a>  <span class="fu">filter</span>(wk2 <span class="sc">&gt;</span> wk1)</span>
<span id="cb82-536"><a href="#cb82-536"></a><span class="in">```</span></span>
<span id="cb82-537"><a href="#cb82-537"></a></span>
<span id="cb82-538"><a href="#cb82-538"></a><span class="fu">#### Part c {.unnumbered}</span></span>
<span id="cb82-539"><a href="#cb82-539"></a></span>
<span id="cb82-540"><a href="#cb82-540"></a>Define a new dataset, <span class="in">`nov_1999`</span>, which:</span>
<span id="cb82-541"><a href="#cb82-541"></a></span>
<span id="cb82-542"><a href="#cb82-542"></a><span class="ss">-   </span>only includes data on songs that entered the Billboard charts on November 6, 1999</span>
<span id="cb82-543"><a href="#cb82-543"></a><span class="ss">-   </span>keeps all variables *except* <span class="in">`track`</span> and <span class="in">`date.entered`</span>. HINT: How can you avoid writing out all the variable names you want to keep?</span>
<span id="cb82-544"><a href="#cb82-544"></a></span>
<span id="cb82-547"><a href="#cb82-547"></a><span class="in">```{r}</span></span>
<span id="cb82-548"><a href="#cb82-548"></a><span class="co"># Define nov_1999</span></span>
<span id="cb82-549"><a href="#cb82-549"></a>nov_1999 <span class="ot">&lt;-</span> billboard <span class="sc">|&gt;</span></span>
<span id="cb82-550"><a href="#cb82-550"></a>  <span class="fu">filter</span>(date.entered <span class="sc">==</span> <span class="st">"1999-11-06"</span>) <span class="sc">|&gt;</span></span>
<span id="cb82-551"><a href="#cb82-551"></a>  <span class="fu">select</span>(<span class="sc">-</span>track, <span class="sc">-</span>date.entered)</span>
<span id="cb82-552"><a href="#cb82-552"></a></span>
<span id="cb82-553"><a href="#cb82-553"></a><span class="co"># Confirm that nov_1999 has 2 rows (songs) and 77 columns</span></span>
<span id="cb82-554"><a href="#cb82-554"></a><span class="fu">dim</span>(nov_1999)</span>
<span id="cb82-555"><a href="#cb82-555"></a><span class="fu">head</span>(nov_1999)</span>
<span id="cb82-556"><a href="#cb82-556"></a></span>
<span id="cb82-557"><a href="#cb82-557"></a><span class="in">```</span></span>
<span id="cb82-558"><a href="#cb82-558"></a></span>
<span id="cb82-559"><a href="#cb82-559"></a><span class="fu">#### Part d {.unnumbered}</span></span>
<span id="cb82-560"><a href="#cb82-560"></a></span>
<span id="cb82-561"><a href="#cb82-561"></a>Create and discuss a visualization of the rankings (y-axis) over time (x-axis) for the 2 songs in <span class="in">`nov_1999`</span>. There are hints below (if you scroll), but you're encouraged to play around and use as few hints as possible.</span>
<span id="cb82-562"><a href="#cb82-562"></a></span>
<span id="cb82-565"><a href="#cb82-565"></a><span class="in">```{r}</span></span>
<span id="cb82-566"><a href="#cb82-566"></a>nov_1999 <span class="sc">|&gt;</span> </span>
<span id="cb82-567"><a href="#cb82-567"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>artist, <span class="at">names_to =</span> <span class="st">"week"</span>, <span class="at">names_prefix =</span> <span class="st">"wk"</span>, <span class="at">values_to =</span> <span class="st">"rank"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb82-568"><a href="#cb82-568"></a>  <span class="fu">mutate</span>(<span class="at">week =</span> <span class="fu">as.numeric</span>(week)) <span class="sc">|&gt;</span> </span>
<span id="cb82-569"><a href="#cb82-569"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> rank, <span class="at">x =</span> week, <span class="at">color =</span> artist)) <span class="sc">+</span> </span>
<span id="cb82-570"><a href="#cb82-570"></a>    <span class="fu">geom_line</span>()</span>
<span id="cb82-571"><a href="#cb82-571"></a><span class="in">```</span></span>
<span id="cb82-572"><a href="#cb82-572"></a></span>
<span id="cb82-573"><a href="#cb82-573"></a>Hints:</span>
<span id="cb82-574"><a href="#cb82-574"></a></span>
<span id="cb82-575"><a href="#cb82-575"></a><span class="ss">-   </span>Should you first pivot wider or longer?</span>
<span id="cb82-576"><a href="#cb82-576"></a><span class="ss">-   </span>Once you pivot, the week number is turned into a character variable. How can you change it to a number?</span>
<span id="cb82-577"><a href="#cb82-577"></a></span>
<span id="cb82-578"><a href="#cb82-578"></a>\</span>
<span id="cb82-579"><a href="#cb82-579"></a>\</span>
<span id="cb82-580"><a href="#cb82-580"></a>\</span>
<span id="cb82-581"><a href="#cb82-581"></a>\</span>
<span id="cb82-582"><a href="#cb82-582"></a></span>
<span id="cb82-583"><a href="#cb82-583"></a><span class="fu">### Exercise 6: Practice with the Daily Show {.unnumbered}</span></span>
<span id="cb82-584"><a href="#cb82-584"></a></span>
<span id="cb82-585"><a href="#cb82-585"></a>The data associated with <span class="co">[</span><span class="ot">this article</span><span class="co">](https://fivethirtyeight.com/datalab/every-guest-jon-stewart-ever-had-on-the-daily-show/)</span> is available in the <span class="in">`fivethirtyeight`</span> package, and is loaded into <span class="in">`daily`</span> below. It includes a list of every guest to ever appear on Jon Stewart's The Daily Show, a "late-night talk and satirical news" program (per Wikipedia). Check out the dataset and note that when multiple people appeared together, each person receives their own line:</span>
<span id="cb82-586"><a href="#cb82-586"></a></span>
<span id="cb82-589"><a href="#cb82-589"></a><span class="in">```{r}</span></span>
<span id="cb82-590"><a href="#cb82-590"></a><span class="fu">library</span>(fivethirtyeight)</span>
<span id="cb82-591"><a href="#cb82-591"></a><span class="fu">data</span>(<span class="st">"daily_show_guests"</span>)</span>
<span id="cb82-592"><a href="#cb82-592"></a>daily <span class="ot">&lt;-</span> daily_show_guests</span>
<span id="cb82-593"><a href="#cb82-593"></a><span class="in">```</span></span>
<span id="cb82-594"><a href="#cb82-594"></a></span>
<span id="cb82-595"><a href="#cb82-595"></a>In analyzing this data, you'll need to determine if and when the data needs to be reshaped.</span>
<span id="cb82-596"><a href="#cb82-596"></a></span>
<span id="cb82-597"><a href="#cb82-597"></a><span class="fu">#### Part a {.unnumbered}</span></span>
<span id="cb82-598"><a href="#cb82-598"></a></span>
<span id="cb82-599"><a href="#cb82-599"></a>Identify the 15 guests that appeared the most. (This isn't a very diverse guest list!)</span>
<span id="cb82-600"><a href="#cb82-600"></a></span>
<span id="cb82-603"><a href="#cb82-603"></a><span class="in">```{r}</span></span>
<span id="cb82-604"><a href="#cb82-604"></a>daily <span class="sc">|&gt;</span></span>
<span id="cb82-605"><a href="#cb82-605"></a>  <span class="fu">count</span>(raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb82-606"><a href="#cb82-606"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb82-607"><a href="#cb82-607"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span>
<span id="cb82-608"><a href="#cb82-608"></a><span class="in">```</span></span>
<span id="cb82-609"><a href="#cb82-609"></a></span>
<span id="cb82-610"><a href="#cb82-610"></a><span class="fu">#### Part b {.unnumbered}</span></span>
<span id="cb82-611"><a href="#cb82-611"></a></span>
<span id="cb82-612"><a href="#cb82-612"></a>CHALLENGE: Create the following data set containing 19 columns:</span>
<span id="cb82-613"><a href="#cb82-613"></a></span>
<span id="cb82-614"><a href="#cb82-614"></a><span class="ss">-   </span>The first column should have the 15 guests with the highest number of total appearances on the show, listed in descending order of number of appearances.</span>
<span id="cb82-615"><a href="#cb82-615"></a><span class="ss">-   </span>17 columns should show the number of appearances of the corresponding guest in each year from 1999 to 2015 (one per column).</span>
<span id="cb82-616"><a href="#cb82-616"></a><span class="ss">-   </span>Another column should show the total number of appearances for the corresponding guest over the entire duration of the show.</span>
<span id="cb82-617"><a href="#cb82-617"></a></span>
<span id="cb82-618"><a href="#cb82-618"></a>There are hints below (if you scroll), but you're encouraged to play around and use as few hints as possible.</span>
<span id="cb82-619"><a href="#cb82-619"></a></span>
<span id="cb82-622"><a href="#cb82-622"></a><span class="in">```{r}</span></span>
<span id="cb82-623"><a href="#cb82-623"></a>wide_daily_guest <span class="ot">&lt;-</span> daily <span class="sc">|&gt;</span></span>
<span id="cb82-624"><a href="#cb82-624"></a>  <span class="fu">count</span>(year, raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb82-625"><a href="#cb82-625"></a>  <span class="fu">group_by</span>(raw_guest_list) <span class="sc">|&gt;</span></span>
<span id="cb82-626"><a href="#cb82-626"></a>  <span class="fu">mutate</span>(<span class="at">total =</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb82-627"><a href="#cb82-627"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> year, <span class="at">values_from =</span> n, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb82-628"><a href="#cb82-628"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total))</span>
<span id="cb82-629"><a href="#cb82-629"></a>  </span>
<span id="cb82-630"><a href="#cb82-630"></a>  <span class="fu">head</span>(wide_daily_guest, <span class="dv">15</span>)</span>
<span id="cb82-631"><a href="#cb82-631"></a></span>
<span id="cb82-632"><a href="#cb82-632"></a><span class="in">```</span></span>
<span id="cb82-633"><a href="#cb82-633"></a></span>
<span id="cb82-634"><a href="#cb82-634"></a>HINTS: There are lots of ways to do this. You don't necessarily need all of these hints.</span>
<span id="cb82-635"><a href="#cb82-635"></a></span>
<span id="cb82-636"><a href="#cb82-636"></a><span class="ss">-   </span>First obtain the number of times a guest appears each year.</span>
<span id="cb82-637"><a href="#cb82-637"></a><span class="ss">-   </span>To this, add a new column which includes the total number of times a guest appears across all years.</span>
<span id="cb82-638"><a href="#cb82-638"></a><span class="ss">-   </span>Pivot (longer or wider?). When you do, use <span class="in">`values_fill = 0`</span> to replace NA values with 0.</span>
<span id="cb82-639"><a href="#cb82-639"></a><span class="ss">-   </span>Arrange, then and keep the top 15.</span>
<span id="cb82-640"><a href="#cb82-640"></a></span>
<span id="cb82-641"><a href="#cb82-641"></a><span class="fu">#### Part c {.unnumbered}</span></span>
<span id="cb82-642"><a href="#cb82-642"></a></span>
<span id="cb82-643"><a href="#cb82-643"></a>Let's recreate the first figure from <span class="co">[</span><span class="ot">the article</span><span class="co">](https://fivethirtyeight.com/datalab/every-guest-jon-stewart-ever-had-on-the-daily-show/)</span>. This groups all guests into 3 broader occupational categories. However, our current data has 18 categories:</span>
<span id="cb82-644"><a href="#cb82-644"></a></span>
<span id="cb82-647"><a href="#cb82-647"></a><span class="in">```{r}</span></span>
<span id="cb82-648"><a href="#cb82-648"></a>daily <span class="sc">|&gt;</span> </span>
<span id="cb82-649"><a href="#cb82-649"></a>  <span class="fu">count</span>(group)</span>
<span id="cb82-650"><a href="#cb82-650"></a><span class="in">```</span></span>
<span id="cb82-651"><a href="#cb82-651"></a></span>
<span id="cb82-652"><a href="#cb82-652"></a>Let's define a new dataset that includes a new variable, <span class="in">`broad_group`</span>, that buckets these 18 categories into the 3 bigger ones used in the article. And get rid of any rows missing information on <span class="in">`broad_group`</span>. You'll learn the code soon! For now, just run this chunk:</span>
<span id="cb82-653"><a href="#cb82-653"></a></span>
<span id="cb82-656"><a href="#cb82-656"></a><span class="in">```{r}</span></span>
<span id="cb82-657"><a href="#cb82-657"></a>plot_data <span class="ot">&lt;-</span> daily <span class="sc">|&gt;</span> </span>
<span id="cb82-658"><a href="#cb82-658"></a>  <span class="fu">mutate</span>(<span class="at">broad_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb82-659"><a href="#cb82-659"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Acting"</span>, <span class="st">"Athletics"</span>, <span class="st">"Comedy"</span>, <span class="st">"Musician"</span>) <span class="sc">~</span> <span class="st">"Acting, Comedy &amp; Music"</span>,</span>
<span id="cb82-660"><a href="#cb82-660"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Media"</span>, <span class="st">"media"</span>, <span class="st">"Science"</span>, <span class="st">"Academic"</span>, <span class="st">"Consultant"</span>, <span class="st">"Clergy"</span>) <span class="sc">~</span> <span class="st">"Media"</span>,</span>
<span id="cb82-661"><a href="#cb82-661"></a>    group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Politician"</span>, <span class="st">"Political Aide"</span>, <span class="st">"Government"</span>, <span class="st">"Military"</span>, <span class="st">"Business"</span>, <span class="st">"Advocacy"</span>) <span class="sc">~</span> <span class="st">"Government and Politics"</span>,</span>
<span id="cb82-662"><a href="#cb82-662"></a>    <span class="at">.default =</span> <span class="cn">NA</span></span>
<span id="cb82-663"><a href="#cb82-663"></a>  )) <span class="sc">|&gt;</span> </span>
<span id="cb82-664"><a href="#cb82-664"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(broad_group))</span>
<span id="cb82-665"><a href="#cb82-665"></a><span class="in">```</span></span>
<span id="cb82-666"><a href="#cb82-666"></a></span>
<span id="cb82-667"><a href="#cb82-667"></a>Now, using the <span class="in">`broad_group`</span> variable in <span class="in">`plot_data`</span>, recreate the graphic from the article, with three different lines showing the fraction of guests in each group over time. Note: You'll have to wrangle the data first.</span>
<span id="cb82-668"><a href="#cb82-668"></a></span>
<span id="cb82-671"><a href="#cb82-671"></a><span class="in">```{r}</span></span>
<span id="cb82-672"><a href="#cb82-672"></a>plot_data <span class="sc">|&gt;</span></span>
<span id="cb82-673"><a href="#cb82-673"></a>  <span class="fu">group_by</span>(year, broad_group) <span class="sc">|&gt;</span></span>
<span id="cb82-674"><a href="#cb82-674"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb82-675"><a href="#cb82-675"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb82-676"><a href="#cb82-676"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> freq, <span class="at">color =</span> broad_group)) <span class="sc">+</span></span>
<span id="cb82-677"><a href="#cb82-677"></a>  <span class="fu">geom_line</span>()</span>
<span id="cb82-678"><a href="#cb82-678"></a>  </span>
<span id="cb82-679"><a href="#cb82-679"></a><span class="in">```</span></span>
<span id="cb82-680"><a href="#cb82-680"></a></span>
<span id="cb82-681"><a href="#cb82-681"></a>\</span>
<span id="cb82-682"><a href="#cb82-682"></a>\</span>
<span id="cb82-683"><a href="#cb82-683"></a>\</span>
<span id="cb82-684"><a href="#cb82-684"></a>\</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>